import { Printer, FilamentType, FilamentBrand } from './types';

export const printers: Printer[] = [
  // --- BAMBU LAB ---
  {
    id: 'b-a1mini',
    brand: 'Bambu Lab',
    name: 'A1 Mini',
    price: 189,
    comboPrice: 299,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '180x180x180mm',
    filaments: ['PLA', 'PETG', 'TPU', 'PVA'],
    maxNozzleTemp: 300,
    maxBedTemp: 80,
    nozzleType: 'Acier Inoxydable',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier',
    maxSpeed: 500,
    maxAcceleration: '10 000 mm/s² (10 m/s²)',
    maxFlow: '28 mm³/s @ABS',
    chassis: 'Acier + Aluminium Extrudé',
    dimensions: '347 × 315 × 365 mm³',
    weight: '5.5 kg',
    screen: '2.4" tactile couleur IPS (320 × 240)',
    camera: 'Caméra basse cadence (jusqu\'à 1080P) avec Time-lapse',
    sensors: ['Fin de filament', 'Odométrie de filament', 'Reprise après coupure', 'Détection d’enchevêtrement (Tangle)'],
    multicolor: { supported: true, system: 'AMS Lite' },
    newTech: 'Active Flow Rate Compensation, Moteurs ultra-silencieux',
    pros: ['Plug & Play et étalonnage tout-en-un', 'Très silencieuse', 'Qualité d\'impression exemplaire'],
    cons: ['Volume compact (180mm)', 'Châssis ouvert (ABS/ASA non recommandés)'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'b-a1',
    brand: 'Bambu Lab',
    name: 'A1',
    price: 259,
    comboPrice: 369,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'TPU', 'PVA'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Inoxydable',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé (Hardened Steel)',
    maxSpeed: 500,
    maxAcceleration: '10 000 mm/s²',
    maxFlow: '28 mm³/s @ABS',
    chassis: 'Acier + Aluminium Extrudé',
    dimensions: '385 × 410 × 430 mm³',
    weight: '8.3 kg',
    screen: '3.5" tactile couleur IPS (320 × 240)',
    camera: 'Caméra basse cadence (jusqu\'à 1080P) avec Time-lapse',
    sensors: ['Fin de filament', 'Odométrie de filament', 'Reprise après coupure', 'Détection d’enchevêtrement (Tangle)'],
    multicolor: { supported: true, system: 'AMS Lite' },
    newTech: 'Buse à changement rapide sans outil, Active Noise Cancellation',
    pros: ['Vitesse impressionnante 500 mm/s', 'Changement de buse ultra-rapide', 'Plateau chauffant jusqu\'à 100°C'],
    cons: ['Structure ouverte (ABS/ASA non recommandés)'],
    image: 'https://images.unsplash.com/photo-1701162444317-036f32e2d097?q=80&w=800'
  },
  {
    id: 'b-a2l',
    brand: 'Bambu Lab',
    name: 'A2L',
    price: 379,
    comboPrice: 489,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '330x320x325mm',
    filaments: ['PLA', 'PETG', 'TPU', 'PVA', 'PLA-CF*', 'PETG-CF*'],
    maxNozzleTemp: 300,
    maxBedTemp: 80,
    nozzleType: 'Acier Inoxydable (Acier Trempé pour CF)',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé',
    maxSpeed: 500,
    maxAcceleration: '10 000 mm/s² (10 m/s²)',
    maxFlow: '28 mm³/s',
    chassis: 'Aluminium et Acier (Cadre extérieur plastique)',
    dimensions: '544 × 529 × 505 mm³',
    weight: '12.8 kg',
    screen: '3.5" tactile couleur (240 × 320)',
    camera: 'Caméra 1080P avec Time-lapse',
    sensors: ['Fin de filament', 'Détection d’enchevêtrement', 'Odométrie', 'Reprise coupure', 'Détection d’agglomération (Clumping Detection)'],
    cuttingModule: 'Module découpe papier/vinyle/cuir (lame 45° 50-600 gf) et dessin stylo (300×255 mm)',
    multicolor: { supported: true, system: 'AMS Lite Gen 2' },
    newTech: 'Moteur d\'extrusion Servo, Détection d’agglomération (Clumping Detection), Module de découpe & dessin',
    pros: ['Grand volume utile 330×320×325 mm', 'Module de découpe & dessin hybride', 'Moteur Servo haute précision'],
    cons: ['Châssis ouvert (plateau limité à 80°C)'],
    image: 'https://images.unsplash.com/photo-1701162444317-036f32e2d097?q=80&w=800'
  },
  {
    id: 'b-p1p',
    brand: 'Bambu Lab',
    name: 'P1P',
    price: 499,
    discontinued: true,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Inoxydable',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier',
    maxSpeed: 500,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '32 mm³/s @ABS',
    chassis: 'Acier',
    dimensions: '386 × 389 × 458 mm³',
    weight: '9.65 kg',
    screen: '2.7" 192 × 64 monochrome avec boutons',
    multicolor: { supported: true, system: 'AMS' },
    newTech: 'CoreXY Haute Vitesse',
    pros: ['Ancien classique très rapide'],
    cons: ['Modèle discontinué', 'Pas de caisson d\'origine'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'b-p1s',
    brand: 'Bambu Lab',
    name: 'P1S',
    price: 379,
    comboPrice: 529,
    variants: [
      { name: 'Sans Combo', price: 379 },
      { name: 'Combo AMS classique', price: 529 },
      { name: 'Combo AMS 2 (Nouvel AMS)', price: 549 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'ABS', 'ASA', 'PVA', 'PET', 'PA', 'PC'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Inoxydable',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier',
    maxSpeed: 500,
    maxAcceleration: '20 000 mm/s² (20 m/s²)',
    maxFlow: '32 mm³/s @ABS',
    chassis: 'Acier (Coque plastique & verre)',
    dimensions: '389 × 389 × 458 mm³',
    weight: '12.95 kg',
    screen: '2.7" 192 × 64 monochrome avec boutons',
    camera: 'Caméra de chambre 720P (0.5 fps) avec Time-lapse',
    filtration: 'Filtre à charbon actif',
    sensors: ['Fin de filament', 'Reprise après coupure', 'Odométrie (avec AMS)'],
    multicolor: { supported: true, system: 'AMS / AMS 2' },
    newTech: 'Chambre fermée filtrée, CoreXY haute performance, Ventilateur régulateur de chambre',
    pros: ['Rapport qualité/prix imbattable', 'Boîtier fermé pour ABS/ASA', 'Très grande communauté'],
    cons: ['Écran monochrome 2.7" à boutons', 'Caméra 0.5 fps basse cadence'],
    image: 'https://images.unsplash.com/photo-1701162444265-d018721c4b22?q=80&w=800'
  },
  {
    id: 'b-p2s',
    brand: 'Bambu Lab',
    name: 'P2S',
    price: 519,
    comboPrice: 699,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'ABS', 'ASA', 'TPU', 'PA', 'PC', 'PVA', 'PLA-CF', 'PETG-CF', 'ABS-GF', 'ASA-CF', 'PA6-CF', 'PA6-GF', 'PAHT-CF', 'PPA-CF', 'PET-CF'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé (Hardened Steel)',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '40 mm³/s',
    chassis: 'Plastique et Acier (Coque plastique & verre)',
    dimensions: '392 × 406 × 478 mm³',
    weight: '14.9 kg',
    screen: '5" tactile couleur HD (854 × 480)',
    camera: 'Caméra HD 1080P fluide à 30 fps intégrée',
    filtration: 'Charbon actif granulé de noix de coco (VOC & Particules)',
    sensors: ['Capteur de porte', 'Fin de filament', 'Détection d’enchevêtrement', 'Odométrie (avec AMS)', 'Reprise coupure'],
    multicolor: { supported: true, system: 'AMS 2.0' },
    newTech: 'Moteur synchrone PMSM haute précision, Caméra 1080P 30fps HD, Processeur Quad-Core avec NPU 2 TOPS',
    pros: ['Vitesse 600 mm/s et buse acier trempé de série', 'Écran tactile couleur 5" HD et caméra 30 fps', 'Filtration charbon noix de coco et Wi-Fi double bande'],
    cons: ['Prix supérieur au P1S'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'b-h2d',
    brand: 'Bambu Lab',
    name: 'H2D',
    price: 1549,
    comboPrice: 1749,
    variants: [
      { name: 'Seule', price: 1549 },
      { name: 'Combo AMS', price: 1749 },
      { name: 'Combo + Laser 10W', price: 2149 },
      { name: 'Combo + Laser 40W', price: 2549 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '325x320x325mm (Double buse : 300x320x325mm | Total: 350x320x325mm)',
    filaments: ['PLA', 'PETG', 'TPU', 'PVA', 'BVOH', 'ABS', 'ASA', 'PC', 'PA', 'PET', 'PPS', 'Composites Carbone/Verre'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé (Double Buse)',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé',
    maxSpeed: 1000,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '40 mm³/s (Standard) / 65 mm³/s (High Flow optionnel)',
    chassis: 'Aluminium, Acier, Plastique et Verre',
    chamberHeating: 'Chauffage actif de la chambre jusqu\'à 65 °C',
    filtration: 'Préfiltre G3 + Filtre HEPA H12 + Charbon actif noix de coco',
    dimensions: '492 × 514 × 626 mm³',
    weight: '31 kg',
    screen: '5" tactile couleur HD (720 × 1280)',
    camera: 'Quadruple caméra : Live View 1080P, Caméra Buse 1080P, Toolhead 1080P, BirdsEye 3264×2448 (Laser)',
    sensors: ['Capteur de porte', 'Fin de filament', 'Détection d’enchevêtrement', 'Odométrie (avec AMS)', 'Reprise coupure'],
    laserModule: 'Modules Laser 10W (400 mm/s, coupe 5mm) ou 40W (1000 mm/s, coupe 15mm contreplaqué)',
    cuttingModule: 'Module découpe 300×285 mm² & traçage stylo 300×255 mm²',
    multicolor: { supported: true, system: 'Vortex / Dual Nozzle' },
    newTech: 'Double buses indépendantes 350°C, Vitesse extrême 1000 mm/s, Chauffage chambre 65°C, Modules Laser 10W/40W',
    pros: ['Double buse haute température 350°C sans purge', 'Vitesse 1000 mm/s et débit jusqu\'à 65 mm³/s', 'Option gravure & découpe laser 10W/40W', 'Chambre chauffée activement 65°C'],
    cons: ['Machine professionnelle haut de gamme'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'b-h2s',
    brand: 'Bambu Lab',
    name: 'H2S',
    price: 1099,
    comboPrice: 1299,
    variants: [
      { name: 'Seule', price: 1099 },
      { name: 'Combo AMS', price: 1299 },
      { name: 'Combo + Laser 10W', price: 1699 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '340x320x340mm',
    filaments: ['PLA', 'PETG', 'TPU', 'PVA', 'BVOH', 'ABS', 'ASA', 'PC', 'PA', 'PET', 'PPS', 'Composites Carbone/Verre'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé',
    maxSpeed: 1000,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '40 mm³/s (Standard) / 65 mm³/s (High Flow optionnel)',
    chassis: 'Aluminium et Acier',
    chamberHeating: 'Chauffage actif de la chambre jusqu\'à 65 °C',
    filtration: 'Préfiltre G3 + Filtre HEPA H12 + Charbon actif noix de coco',
    dimensions: '492 × 514 × 626 mm³',
    weight: '30 kg',
    screen: '5" tactile couleur HD (720 × 1280)',
    camera: 'Triple caméra : Live View 1080P, Toolhead 1600×1200, BirdsEye 3264×2448 (Laser)',
    sensors: ['Capteur de porte', 'Fin de filament', 'Détection d’enchevêtrement', 'Odométrie avec AMS', 'Reprise coupure'],
    laserModule: 'Module Laser 10W (455nm, 400 mm/s, coupe 5mm contreplaqué, classe 1, Lidar Z)',
    cuttingModule: 'Module découpe 297.5×300 mm² & traçage stylo 300×255 mm²',
    multicolor: { supported: true, system: 'Vortex / AMS' },
    newTech: 'Buse 350°C, Vitesse 1000 mm/s, Chauffage chambre 65°C, Compatible Module Laser 10W',
    pros: ['Grand volume 340×320×340 mm', 'Buse 350°C et chambre active 65°C', 'Écosystème hybride 3D + Laser + Découpe'],
    cons: ['Machine imposante (30 kg)'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'b-h2c',
    brand: 'Bambu Lab',
    name: 'H2C',
    price: 2149,
    comboPrice: 2149,
    variants: [
      { name: 'Combo obligatoire', price: 2149 },
      { name: 'Combo + Laser 10W', price: 2549 },
      { name: 'Combo + Laser 40W', price: 2949 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '340x320x340mm',
    filaments: ['Tous', 'PLA', 'PETG', 'TPU', 'PVA', 'BVOH', 'ABS', 'ASA', 'PC', 'PA', 'PET', 'PPS', 'Composites Carbone/Verre'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé',
    maxSpeed: 1000,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '40 mm³/s (Standard) / 65 mm³/s (High Flow)',
    chassis: 'Aluminium et Acier',
    chamberHeating: 'Chauffage actif de la chambre jusqu\'à 65 °C',
    filtration: 'Préfiltre G3 + Filtre HEPA H12 + Charbon actif noix de coco',
    dimensions: '492 × 514 × 626 mm³',
    weight: '33 kg',
    screen: '5" tactile couleur HD (720 × 1280)',
    camera: 'Multi-caméras IA haute résolution 1080P et BirdsEye',
    sensors: ['Capteur de porte', 'Fin de filament', 'Détection d’enchevêtrement', 'Odométrie avec AMS', 'Reprise coupure'],
    laserModule: 'Modules Laser 10W ou 40W haute puissance',
    multicolor: { supported: true, system: 'Vortex Pro' },
    newTech: 'Triple/Quad buses, Vortex cooling, Module Laser optionnel',
    pros: ['Sommet de gamme absolu', 'Multicolore ultra rapide sans purge', 'Pro'],
    cons: ['Prix très élevé'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'b-x1c',
    brand: 'Bambu Lab',
    name: 'X1C (X1-Carbon)',
    price: 1199,
    discontinued: true,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['Tous', 'PLA', 'PETG', 'ABS', 'ASA', 'PA', 'PC', 'Composites CF'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé',
    maxSpeed: 500,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '32 mm³/s',
    chassis: 'Aluminium soudé et Coque verre/métal',
    dimensions: '389 × 389 × 457 mm³',
    weight: '14.13 kg',
    screen: '5" tactile couleur 1280 × 720',
    camera: 'Caméra HD 1080P avec LiDAR double',
    filtration: 'Filtre à charbon actif',
    sensors: ['LiDAR Micro', 'Capteur de porte', 'Fin de filament', 'Reprise coupure'],
    multicolor: { supported: true, system: 'AMS' },
    newTech: 'Double LiDAR IA, Détection automatique de spaghettis',
    pros: ['Pionnière des imprimantes IA intelligentes'],
    cons: ['Modèle discontinué (remplacé par X2D / P2S)'],
    image: 'https://images.unsplash.com/photo-1701162444317-036f32e2d097?q=80&w=800'
  },
  {
    id: 'b-x2d',
    brand: 'Bambu Lab',
    name: 'X2D',
    price: 629,
    comboPrice: 849,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '256x256x260mm (Double buse : 235.5x256x256mm | Total: 256x256x260mm)',
    filaments: ['Tous', 'PLA', 'PETG', 'ABS', 'ASA', 'TPU', 'PA', 'PC', 'PVA', 'Composites Carbone/Verre'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé (Buse principale & auxiliaire)',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé',
    maxSpeed: 1000,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '40 mm³/s',
    chassis: 'Plastique et Acier (Cadre plastique, verre et métal)',
    chamberHeating: 'Chauffage actif de la chambre jusqu\'à 65 °C',
    filtration: 'Préfiltre G3 + Filtre HEPA H12 + Charbon actif noix de coco (VOC & Particules)',
    dimensions: '392 × 406 × 478 mm³',
    weight: '16.25 kg',
    screen: '5" tactile couleur HD (1280 × 720)',
    camera: 'Double caméra : Live View 1080P + Toolhead 1600×1200',
    sensors: ['Capteur de porte', 'Fin de filament', 'Détection d’enchevêtrement', 'Odométrie (avec AMS)', 'Reprise coupure'],
    multicolor: { supported: true, system: 'AMS Gen 2 / Double Buse' },
    newTech: 'Double buse indépendante ID/Auxiliaire, Vitesse extrême 1000 mm/s, Chauffage actif de chambre 65°C, NPU dédié',
    pros: ['Vitesse record de 1000 mm/s', 'Chambre chauffée activement jusqu\'à 65°C', 'Double buse sans gaspillage de purge', 'Filtration HEPA H12 + Charbon'],
    cons: ['Machine haut de gamme avancée'],
    image: 'https://images.unsplash.com/photo-1701162444317-036f32e2d097?q=80&w=800'
  },

  // --- CREALITY ---
  {
    id: 'c-i7',
    brand: 'Creality',
    name: 'i7 Color Combo',
    price: 259,
    comboPrice: 339,
    variants: [
      { name: 'Seule', price: 259 },
      { name: 'Combo CFS Nano', price: 299 },
      { name: 'Combo Autofill', price: 309 },
      { name: 'Combo CFS Lite Color', price: 339 }
    ],
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '260x260x255mm',
    filaments: ['PLA', 'PLA-Silk', 'PLA-CF', 'PETG'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Trempé à démontage rapide sans outil',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier All-Metal Direct Drive avec cutter en acier inoxydable',
    maxSpeed: 500,
    maxAcceleration: '10 000 mm/s²',
    maxFlow: '23 mm³/s',
    chassis: 'Châssis rigide Métal et Plastique',
    dimensions: '470 × 423 × 456 mm³',
    weight: '9.12 kg',
    screen: '2.85" tactile couleur IPS (640 × 480)',
    camera: 'Caméra 720P avec éclairage LED d’appoint et Moniteur IA (spaghetti, détection plateau)',
    sensors: ['Fin de filament', 'Reprise après coupure', 'Input Shaping (correction des vibrations)', 'Surveillance d’extrusion à vide', 'Détection état du cutter', 'Indicateur d’état RGB'],
    multicolor: { supported: true, system: 'CFS Lite / Nano (jusqu’à 4 couleurs)' },
    newTech: 'Moniteur IA 720p avec détection de plateau et spaghettis, Buse acier trempé démontage rapide sans outil, Indicateur LED RGB',
    pros: ['Prix multicolore très agressif à 259 €', 'Caméra IA et Input Shaping inclus', 'Buse acier trempé démontable sans outil', 'Plateau PEI texturé doré double face'],
    cons: ['Structure ouverte (pas d’enceinte fermée)'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'c-k2se',
    brand: 'Creality',
    name: 'K2 SE',
    price: 289,
    comboPrice: 399,
    variants: [
      { name: 'K2 SE (Seule)', price: 289 },
      { name: 'K2 SE Combo (CFS 4 couleurs)', price: 399 }
    ],
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '220x215x245mm',
    filaments: ['PLA', 'PETG', 'ABS', 'ASA', 'TPU', 'PLA-CF'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Trempé / Laiton nouvelle génération',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé nouvelle génération Direct Drive',
    maxSpeed: 500,
    maxAcceleration: '15 000 mm/s²',
    maxFlow: '26 mm³/s',
    chassis: 'Châssis métallique solide en alliage d’aluminium moulé unibody',
    dimensions: '385 × 385 × 450 mm³',
    weight: '10.5 kg',
    screen: '4.3" tactile couleur HD',
    camera: 'En option ou intégrée selon pack',
    sensors: ['Nivellement automatique intelligent ciblé sur zone', 'Fin de filament', 'Reprise après coupure', 'Input Shaping'],
    multicolor: { supported: true, system: 'CFS (jusqu’à 16 couleurs avec 4 modules CFS)' },
    newTech: 'Châssis en aluminium moulé, Nivellement intelligent ultra rapide sur zone ciblée, Multicolore jusqu’à 16 couleurs avec CFS',
    pros: ['CoreXY en aluminium moulé très rigide', 'Support jusqu’à 16 couleurs avec le système CFS', 'Alimentation fluide extrudeur nouvelle génération'],
    cons: ['Châssis ouvert (semi-fermé sans porte vitrée)'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-e3v4combo',
    brand: 'Creality',
    name: 'Ender-3 V4 Combo',
    price: 369,
    comboPrice: 369,
    variants: [
      { name: 'Ender-3 V4 Combo (CFS inclus)', price: 369 }
    ],
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '220x220x235mm',
    filaments: ['Hyper-PLA', 'PLA', 'PETG', 'TPU 95A', 'ABS', 'ASA', 'PLA-CF', 'PA-CF'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Buse haute vitesse 300 ℃',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrudeuse à double engrenage à entraînement direct All-Metal',
    maxSpeed: 500,
    maxAcceleration: '12 000 mm/s²',
    maxFlow: '26 mm³/s',
    chassis: 'Aluminium Extrudé et Acier renforcé V4',
    dimensions: '396 × 359 × 456 mm³ (Machine) | 838 × 396 × 456 mm³ (Combo avec CFS)',
    weight: '6.8 kg (Machine seule) | 12.6 kg (Pack CFS)',
    screen: '2.8" tactile couleur',
    sensors: ['Détection d’emmêlement de filament (avec CFS)', 'Relais automatique de filament', 'Fin de filament', 'Reprise coupure', 'Input Shaping', 'Lecteur RFID avec CFS', 'Kit éclairage LED'],
    multicolor: { supported: true, system: 'CFS (Compatible jusqu’à 4 extensions, soit 16 couleurs)' },
    newTech: 'Système CFS avec puce RFID, Relais de bobine automatique, Nivellement entièrement automatique, 8 Go EMMC',
    pros: ['Compatibilité multicolore CFS jusqu’à 16 couleurs', 'Légère (6.8 kg) et très rapide (500 mm/s)', 'Gestion RFID des filaments et relais automatique'],
    cons: ['Machine ouverte', 'Volume standard (220×220×235 mm)'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k2pro',
    brand: 'Creality',
    name: 'K2 Pro',
    price: 549,
    comboPrice: 749,
    variants: [
      { name: 'K2 Pro (Seule)', price: 549 },
      { name: 'K2 Pro Combo (CFS 4 couleurs)', price: 749 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '300x300x300mm',
    filaments: ['PLA', 'PETG', 'PET', 'ABS', 'ASA', 'PLA-CF', 'PA-CF', 'PPA-CF', 'Tous matériaux techniques'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé haute résistance',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrudeur direct à double engrenage avec moteurs pas-à-pas servo pour axes XY et extrudeur',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '34 mm³/s',
    chassis: 'Châssis unibody moulé en alliage sous pression avec panneaux isolés et porte vitrée',
    chamberHeating: 'Chauffage actif de la chambre jusqu’à 60 ℃',
    filtration: 'Purificateur d’air intégré avec filtre à charbon actif',
    dimensions: '445 × 477 × 573 mm³',
    weight: '23.7 kg',
    screen: '4.3" tactile couleur HD',
    camera: 'Double Caméra IA (1 caméra surveillance live + 1 caméra calibration active)',
    sensors: ['Puce RFID filaments intégrée', 'Relais automatique de filament', 'Détection d’emmêlement', 'Reprise après coupure', 'Input Shaping', 'Éclairage LED', 'Nivellement entièrement automatique'],
    multicolor: { supported: true, system: 'CFS (Compatible jusqu’à 4 extensions, soit 16 couleurs)' },
    newTech: 'Chambre chauffée active jusqu’à 60 ℃, Moteurs pas-à-pas Servo sur XY et extrudeur, Double caméra IA, RFID',
    pros: ['Chambre chauffée activement à 60 ℃ pour matériaux ultra-techniques (PA-CF, PPA-CF)', 'Moteurs servo haute précision en boucle fermée', 'Double caméra IA intégrée', 'Purificateur d’air'],
    cons: ['Poids important (23.7 kg)'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k2plus',
    brand: 'Creality',
    name: 'K2 Plus',
    price: 999,
    comboPrice: 1249,
    variants: [
      { name: 'K2 Plus (Seule)', price: 999 },
      { name: 'K2 Plus Combo (CFS 4 couleurs)', price: 1249 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '350x350x350mm',
    filaments: ['PLA', 'ABS', 'PETG', 'PA-CF', 'PLA-CF', 'PET', 'ASA', 'PPA-CF', 'Tous matériaux industriels'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé haute performance 350 ℃',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrudeuse à entraînement direct à double engrenage haute puissance avec tension active',
    maxSpeed: 600,
    maxAcceleration: '30 000 mm/s² (30 m/s²)',
    maxFlow: '40 mm³/s',
    chassis: 'Châssis industriel mécano-soudé unibody avec tirants en acier et panneaux d’isolation thermique',
    chamberHeating: 'Chauffage actif de la chambre jusqu’à 60 ℃ (Puissance 1200W)',
    filtration: 'Purificateur d’air haute efficacité VOC et particules',
    dimensions: '495 × 515 × 640 mm³ (Machine) | 495 × 515 × 916 mm³ (Combo avec CFS)',
    weight: '35 kg',
    screen: '4.3" tactile couleur HD',
    camera: 'Double Caméra IA Standard (1 surveillance live + 1 étalonnage actif)',
    sensors: ['RFID filaments intégré', 'Calibrage actif inclinaison du lit', 'Tension active de la courroie', 'Relais automatique', 'Détection des enchevêtrements', 'Nivellement entièrement automatique', 'Input Shaping'],
    multicolor: { supported: true, system: 'CFS (Compatible jusqu’à 4 boîtiers, soit 16 couleurs)' },
    newTech: 'Accélération record 30 000 mm/s², Buse 350 ℃, Chambre chauffée active 60 ℃, Tension active de courroie, Étalonnage inclinaison lit',
    pros: ['Volume XXL 350×350×350 mm entièrement fermé et chauffé à 60 ℃', 'Accélération phénoménale de 30 000 mm/s²', 'Buse 350 ℃ pour composites avancés', 'Tension active de courroie et RFID'],
    cons: ['Poids industriel imposant (35 kg)', 'Budget premium'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k1max',
    brand: 'Creality',
    name: 'K1 Max',
    price: 499,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '300x300x300mm',
    filaments: ['ABS', 'PLA', 'PETG', 'PET', 'TPU', 'PA', 'ASA', 'PC', 'PLA-CF', 'PA-CF', 'PET-CF'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Trempé (compatible 0.6 / 0.8 mm)',
    nozzleDiameter: 0.4,
    extruderGears: 'Dual-Gear Direct Drive All-Metal',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '32 mm³/s',
    chassis: 'Châssis en alliage d’aluminium moulé sous pression monobloc',
    chamberHeating: 'Chauffage passif régulé par plateau et caisson fermé',
    filtration: 'Purificateur d’air intégré avec filtre à charbon actif',
    dimensions: '435 × 462 × 526 mm³',
    weight: '18 kg',
    screen: '4.3" tactile couleur',
    camera: 'Caméra IA HD 1080P intégrée + Micro-LiDAR double faisceau',
    sensors: ['AI LiDAR pour calibration premier millimètre', 'Caméra IA détection spaghettis & corps étrangers', 'Fin de filament', 'Reprise coupure', 'Input Shaping'],
    multicolor: { supported: false },
    newTech: 'Double LiDAR IA haute précision (1 µm), Caméra IA intégrée, Vitesse 600 mm/s, Purificateur d’air',
    pros: ['Grand volume fermé 300×300×300 mm à prix très attractif', 'Double LiDAR IA pour première couche parfaite', 'Très rapide et robuste'],
    cons: ['Impression monocouleur uniquement'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k1c',
    brand: 'Creality',
    name: 'K1C',
    price: 349,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'ABS', 'PETG', 'PET', 'TPU', 'PA', 'ASA', 'PC', 'PLA-CF', 'PA-CF', 'PET-CF'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Buse Unicorn intégrée Bimétal / Acier Trempé anti-bouchage',
    nozzleDiameter: 0.4,
    extruderGears: 'Clog-free direct drive All-Metal haute adhérence',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '30 mm³/s',
    chassis: 'Châssis rigide en alliage d’aluminium moulé sous pression',
    chamberHeating: 'Chauffage passif en caisson fermé',
    filtration: 'Purificateur d’air intégré (Air Purifier charbon actif)',
    dimensions: '355 × 355 × 482 mm³',
    weight: '12.4 kg',
    screen: '4.3" tactile couleur',
    camera: 'Caméra IA intégrée (surveillance, time-lapse, détection d’erreurs)',
    sensors: ['Caméra IA avec détection corps étrangers', 'Capteur de fin de filament', 'Reprise coupure', 'Input Shaping (accéléromètre G-Sensor)'],
    multicolor: { supported: false },
    newTech: 'Buse Unicorn anti-bouchage bimétal prête pour composites carbone, Caméra IA incluse, Purificateur d’air',
    pros: ['Prête pour filaments carbone (CF) dès la sortie de boîte', 'Boîtier fermé avec caméra IA et filtration charbon', 'Prix très accessible pour une CoreXY fermée'],
    cons: ['Monocouleur', 'Volume standard (220mm)'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k1',
    brand: 'Creality',
    name: 'K1',
    price: 299,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'PETG', 'ABS'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    extruderGears: 'Dual-Gear Direct Drive',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '32 mm³/s',
    chassis: 'Alliage d’aluminium moulé sous pression',
    chamberHeating: 'Chauffage passif en caisson fermé',
    dimensions: '355 × 355 × 480 mm³',
    weight: '12 kg',
    screen: '4.3" tactile couleur',
    sensors: ['Fin de filament', 'Reprise après coupure', 'Input Shaping'],
    multicolor: { supported: false },
    newTech: 'CoreXY 600 mm/s classique en caisson fermé',
    pros: ['Fermée à moins de 300 €', 'Très rapide'],
    cons: ['Première révision de la série K'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k1se',
    brand: 'Creality',
    name: 'K1 SE',
    price: 279,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'PETG', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Laiton / Acier',
    nozzleDiameter: 0.4,
    extruderGears: 'Direct Drive All-Metal',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '30 mm³/s',
    chassis: 'Structure Open Frame en aluminium moulé',
    dimensions: '355 × 355 × 480 mm³',
    weight: '10.2 kg',
    screen: '4.3" tactile couleur',
    sensors: ['Fin de filament', 'Reprise après coupure', 'Input Shaping'],
    multicolor: { supported: false },
    newTech: 'CoreXY Open Frame ultra rapide',
    pros: ['Ultra rapide 600 mm/s', 'Prix plancher CoreXY'],
    cons: ['Non fermée'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-hi',
    brand: 'Creality',
    name: 'Hi Combo',
    price: 259,
    comboPrice: 259,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '200x200x200mm',
    filaments: ['PLA', 'PETG'],
    maxNozzleTemp: 260,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    extruderGears: 'Direct Drive',
    maxSpeed: 300,
    maxAcceleration: '8 000 mm/s²',
    maxFlow: '18 mm³/s',
    chassis: 'Châssis compact coloré',
    dimensions: '250 × 250 × 270 mm³',
    weight: '6.5 kg',
    screen: '2.8" couleur',
    sensors: ['Fin de filament', 'Reprise après coupure'],
    multicolor: { supported: true, system: 'Hi-Color' },
    newTech: 'Design compact pour jeunes créateurs',
    pros: ['Facile à transporter', 'Ludique et colorée'],
    cons: ['Petit volume 200mm'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-v3ke',
    brand: 'Creality',
    name: 'Ender-3 V3 KE',
    price: 239,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '220x220x240mm',
    filaments: ['PLA', 'PETG', 'ABS', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Buse haute vitesse 300 ℃ en alliage cuivre/acier',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrusion à entraînement direct « Sprite » améliorée',
    maxSpeed: 500,
    maxAcceleration: '8 000 mm/s²',
    maxFlow: '24 mm³/s',
    chassis: 'Aluminium Extrudé avec rail linéaire en acier sur axe X',
    dimensions: '433 × 366 × 490 mm³',
    weight: '7.8 kg',
    screen: '4.3" tactile couleur',
    sensors: ['Mise à niveau automatique mains libres', 'Capteur de fin de filament', 'Reprise coupure', 'Input Shaping'],
    multicolor: { supported: false },
    newTech: 'Creality OS (Klipper) intégré, Rail linéaire axe X, Vitesse 500 mm/s, Buse 300 ℃',
    pros: ['Très rapide (500 mm/s) avec rail linéaire X', 'Klipper natif avec écran tactile', 'Buse 300 ℃ pour PETG/ABS'],
    cons: ['Structure ouverte'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-v3',
    brand: 'Creality',
    name: 'Ender-3 V3 (Original)',
    price: 329,
    discontinued: true,
    enclosed: false,
    structure: 'CoreXZ',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'ABS', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Buse bimétal 0.4 mm',
    nozzleDiameter: 0.4,
    extruderGears: 'Direct Drive Sprite',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '30 mm³/s',
    chassis: 'Structure aluminium moulé sous pression CoreXZ',
    dimensions: '358 × 374 × 498 mm³',
    weight: '8.8 kg',
    screen: '4.3" tactile couleur',
    sensors: ['Fin de filament', 'Reprise coupure', 'Auto-nivellement'],
    multicolor: { supported: false },
    newTech: 'Cinématique CoreXZ haute précision',
    pros: ['Bonne stabilité cinématique CoreXZ'],
    cons: ['Modèle discontinué'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-v3se',
    brand: 'Creality',
    name: 'Ender-3 V3 SE',
    price: 169,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'PETG', 'TPU (95A)'],
    maxNozzleTemp: 260,
    maxBedTemp: 100,
    nozzleType: 'Laiton standard 0.4 mm',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrudeur direct « Sprite » All-Metal',
    maxSpeed: 250,
    maxAcceleration: '2 500 mm/s²',
    maxFlow: '16 mm³/s',
    chassis: 'Aluminium et Acier profilé',
    dimensions: '349 × 364 × 490 mm³',
    weight: '7.34 kg',
    screen: '3.2" couleur avec bouton rotatif de sélection',
    sensors: ['Nivellement automatique avec capteur de contrainte (Strain Gauge) + CR-Touch', 'Reprise après coupure'],
    multicolor: { supported: false },
    newTech: 'Double nivellement automatique mains libres (sans feuille papier), Extrudeur Sprite fiable',
    pros: ['Prix mini (169 €)', 'Nivellement automatique sans prise de tête', 'Idéale pour débuter dans l’impression 3D'],
    cons: ['Structure ouverte', 'Non adaptée ABS (température buse limitée à 260 ℃)'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-v3plus',
    brand: 'Creality',
    name: 'Ender-3 V3 Plus',
    price: 399,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '300x300x330mm',
    filaments: ['Tous', 'PLA', 'PETG', 'ABS', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Buse bimétal haute vitesse',
    nozzleDiameter: 0.4,
    extruderGears: 'Direct Drive Sprite All-Metal',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '30 mm³/s',
    chassis: 'Châssis aluminium sous pression avec double tige de renfort diagonale',
    dimensions: '410 × 445 × 577 mm³',
    weight: '11.5 kg',
    screen: '4.3" tactile couleur',
    sensors: ['Fin de filament', 'Reprise coupure', 'Nivellement automatique'],
    multicolor: { supported: false },
    newTech: 'Châssis double tige de renfort diagonale, Format étendu 300×300 mm',
    pros: ['Grand volume 300mm très abordable', 'Rigidité avec les tirants de renfort'],
    cons: ['Machine ouverte imposante'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-e5max',
    brand: 'Creality',
    name: 'Ender-5 Max',
    price: 799,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '400x400x400mm',
    filaments: ['Hyper PLA', 'PLA', 'PETG', 'TPU95A', 'ABS', 'ASA', 'PLA-CF', 'PA', 'PLA-Silk'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Buse haute performance 0.4 mm (compatible 0.6 / 0.8 mm)',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrudeur Direct Drive haute traction',
    maxSpeed: 700,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '35 mm³/s',
    chassis: 'Structure cubique mécano-soudée haute stabilité en aluminium extrudé lourd',
    dimensions: '649 × 721 × 850 mm³',
    weight: '25.9 kg',
    screen: '4.3" tactile couleur',
    camera: 'En option',
    sensors: ['Nivellement automatique multipoint en 64 points', 'Fin de filament', 'Reprise après coupure', 'Input Shaping (correction des vibrations)', 'Éclairage LED intégré', 'Voyant lumineux d’état RVB'],
    multicolor: { supported: false },
    newTech: 'Structure cubique grand volume 400mm, Vitesse record jusqu’à 700 mm/s, Nivellement 64 points, Puissance 1250W',
    pros: ['Volume gigantesque 400×400×400 mm', 'Vitesse extrême jusqu’à 700 mm/s', 'Structure cubique ultra rigide pour impressions lourdes'],
    cons: ['Encombrement important (85 cm de hauteur)', 'Châssis ouvert'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },

  // --- ANYCUBIC ---
  {
    id: 'a-k2max',
    brand: 'Anycubic',
    name: 'Kobra 2 Max',
    price: 499,
    discontinued: true,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '420x420x500mm',
    filaments: ['PLA', 'PETG', 'TPU', 'ABS'],
    maxNozzleTemp: 260,
    maxBedTemp: 90,
    nozzleType: 'Laiton haute vitesse',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier All-Metal Direct Drive',
    maxSpeed: 500,
    maxAcceleration: '10 000 mm/s²',
    maxFlow: '28 mm³/s',
    chassis: 'Aluminium extrudé et Acier avec tiges de renfort diagonales',
    dimensions: '640 × 735 × 740 mm³',
    weight: '21 kg',
    screen: '4.3" tactile couleur avec interface responsive',
    sensors: ['Fin de filament', 'Reprise après coupure', 'Nivellement LeviQ 2.0 automatique'],
    multicolor: { supported: false },
    newTech: 'Vitesse 500 mm/s sur format géant 420mm de génération précédente',
    pros: ['Volume géant XXL de 88 litres', 'Stabilité avec tirants métalliques', 'Très abordable pour son volume'],
    cons: ['Modèle discontinué (remplacé par Kobra 3 Max & Max V2)', 'Monocouleur (pas de support ACE)', 'Plateau limité à 90 °C'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-k3',
    brand: 'Anycubic',
    name: 'Kobra 3 Combo',
    price: 379,
    comboPrice: 379,
    variants: [
      { name: 'Kobra 3 Combo (ACE Pro)', price: 379 }
    ],
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '250x250x260mm',
    filaments: ['PLA', 'PETG', 'TPU', 'ABS', 'ASA', 'PET'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Bimétal / Acier Trempé à changement rapide',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé (Double engrenage Direct Drive haute traction)',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s² (20 m/s²)',
    maxFlow: '32 mm³/s',
    chassis: 'Alliage d’Aluminium extrudé rigide et Acier renforcé avec double moteur Z synchronisé',
    dimensions: '453 × 505 × 525 mm³ (Imprimante) | 366 × 283 × 235 mm³ (ACE Pro)',
    weight: '9.2 kg (Machine seule) | 13.8 kg (Pack Combo avec ACE Pro)',
    screen: '4.3" tactile couleur capacitif haute sensibilité',
    camera: 'Caméra HD 1080P avec Time-lapse et détection d’anomalies',
    sensors: ['Fin de filament', 'Détection d’enchevêtrement', 'Reprise après coupure', 'Compensation des résonances (Accéléromètre G-Sensor)', 'Détection de colmatage de buse'],
    multicolor: { supported: true, system: 'ACE Pro (Séchage actif jusqu’à 55°C, 4 à 8 couleurs)' },
    newTech: 'Boîtier ACE Pro avec double résistance chauffante PTC (séchage actif en continu), LeviQ 3.0 auto Z-offset, Vitesse 600 mm/s',
    pros: ['Séchage actif des filaments intégré au boîtier 4 couleurs', 'Vitesse impressionnante 600 mm/s', 'Étalonnage LeviQ 3.0 automatique sans réglage feuille', 'Buse démontage rapide'],
    cons: ['Structure ouverte (ABS/ASA sensibles aux courants d’air)', 'Encombrement du boîtier ACE Pro à côté de la machine'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-k3v2',
    brand: 'Anycubic',
    name: 'Kobra 3 V2 Combo',
    price: 329,
    comboPrice: 329,
    variants: [
      { name: 'Kobra 3 V2 Combo (ACE Pro V2)', price: 329 }
    ],
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '250x250x260mm',
    filaments: ['Tous', 'PLA', 'PETG', 'TPU', 'ABS', 'ASA', 'PET', 'Composites légers'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé à démontage rapide',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé haute résistance All-Metal',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '32 mm³/s',
    chassis: 'Aluminium Extrudé haute rigidité & Acier usiné',
    dimensions: '453 × 505 × 525 mm³',
    weight: '9.3 kg (Imprimante) | 14 kg (Pack Combo V2)',
    screen: '4.3" tactile couleur capacitif nouvelle génération',
    camera: 'Caméra HD intégrée avec time-lapse',
    sensors: ['Fin de filament', 'Détection d’enchevêtrement V2', 'Reprise coupure', 'Capteur de vibration d’axe', 'Auto-alignement Z'],
    multicolor: { supported: true, system: 'ACE Pro V2 (Séchage actif optimisé, étanchéité renforcée)' },
    newTech: 'Système ACE Pro V2 fiabilisé, Changement de couleur accéléré, Réduction du bruit d’extrusion',
    pros: ['Rapport qualité/prix imbattable à 329 € avec boîtier séchant', 'Vitesse 600 mm/s de série', 'Buse acier trempé rapide', 'Nivellement ultra réactif'],
    cons: ['Châssis ouvert'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-k3max',
    brand: 'Anycubic',
    name: 'Kobra 3 Max',
    price: 429,
    comboPrice: 499,
    variants: [
      { name: 'Kobra 3 Max (Seule)', price: 429 },
      { name: 'Kobra 3 Max Combo (ACE Pro)', price: 499 }
    ],
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '420x420x500mm',
    filaments: ['Tous', 'PLA', 'PETG', 'TPU', 'ABS'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier / Laiton haute performance 0.4 mm',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé All-Metal Direct Drive',
    maxSpeed: 500,
    maxAcceleration: '10 000 mm/s²',
    maxFlow: '30 mm³/s',
    chassis: 'Aluminium et Acier renforcé avec tirants diagonaux et double axe Z synchronisé',
    dimensions: '640 × 735 × 740 mm³',
    weight: '21 kg',
    screen: '4.3" tactile couleur haute sensibilité',
    camera: 'Caméra HD avec surveillance et Time-lapse',
    sensors: ['Fin de filament', 'Reprise après coupure', 'Nivellement automatique LeviQ 3.0', 'Capteur de tension de courroie'],
    multicolor: { supported: true, system: 'ACE Pro (4 à 8 couleurs)' },
    newTech: 'Plateau géant 420×420 mm avec gestion multizone de chauffe, Renforts anti-vibrations, Multicolore grand format',
    pros: ['Très grand volume utile de 88 litres', 'Compatibilité multicolore avec séchage actif', 'Rigidité structurelle avec barres de renfort'],
    cons: ['Machine très encombrante', 'Plateau lourd limitant l’accélération sur l’axe Y'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-k3max-v2',
    brand: 'Anycubic',
    name: 'Kobra 3 Max V2 Combo',
    price: 569,
    comboPrice: 569,
    variants: [
      { name: 'Combo ACE Pro V2', price: 569 }
    ],
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '420x420x500mm',
    filaments: ['Tous', 'PLA', 'PETG', 'ABS', 'TPU', 'ASA', 'Composites'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé haute résistance',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé haute dureté Direct Drive',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '34 mm³/s',
    chassis: 'Cadre portique aluminium renforcé profilé lourd avec tirants triangulaires en acier',
    dimensions: '640 × 735 × 740 mm³',
    weight: '22.5 kg',
    screen: '4.3" tactile couleur capacitif HD',
    camera: 'Caméra IA HD 1080P intégrée (détection spaghettis & timelapse)',
    sensors: ['Capteur de tension de filament', 'Détection d’enchevêtrement', 'Fin de filament', 'Reprise coupure', 'Compensation active G-Sensor'],
    multicolor: { supported: true, system: 'ACE Pro V2 (inclus)' },
    newTech: 'Pack Max V2 avec boîtier ACE Pro V2, Vitesse poussée à 600 mm/s, Nivellement LeviQ 3.0+, Chauffage multizone dynamique',
    pros: ['Remise exceptionnelle à 569 € (au lieu de 899 €)', 'Volume géant 420×420×500 mm multicolore', 'Boîtier ACE Pro V2 avec séchage double PTC 55°C', 'Vitesse 600 mm/s'],
    cons: ['Châssis ouvert', 'Encombrement important dans l’atelier'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-s1',
    brand: 'Anycubic',
    name: 'Kobra S1',
    price: 349,
    comboPrice: 399,
    variants: [
      { name: 'Kobra S1 (Seule)', price: 349 },
      { name: 'Combo ACE Pro', price: 399 },
      { name: 'Combo ACE 2 Pro', price: 499 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '320x320x350mm',
    filaments: ['Tous', 'PLA', 'PETG', 'ABS', 'ASA', 'TPU', 'PC', 'PA (Nylon)', 'Composites Carbone/Verre'],
    maxNozzleTemp: 320,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé haute résistance',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé All-Metal CoreXY haute précision',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '35 mm³/s',
    chassis: 'Cadre soudé en acier monobloc avec parois aluminium et portes en verre trempé',
    chamberHeating: 'Chauffage passif régulé par chambre étanche et ventilation d’extraction filtrée',
    filtration: 'Filtre à charbon actif haute densité + filtre anti-particules VOC',
    dimensions: '515 × 520 × 610 mm³',
    weight: '24.5 kg',
    screen: '5" tactile couleur HD',
    camera: 'Caméra IA HD 1080P intégrée (détection spaghettis & Time-lapse)',
    sensors: ['Capteur de porte', 'Détection d’enchevêtrement', 'Fin de filament', 'Reprise après coupure', 'Capteur de résonance d’axe CoreXY'],
    multicolor: { supported: true, system: 'ACE Pro / ACE 2 Pro (jusqu’à 16 couleurs)' },
    newTech: 'Cinématique CoreXY haute vitesse 600 mm/s dans caisson fermé 320×320×350 mm, Filtration intégrée, ACE 2 Pro compatible',
    pros: ['Prix promo saisissant à 349 € seule (au lieu de 549 €)', 'Boîtier fermé adapté ABS, ASA, Nylon, PC', 'Caméra IA et filtration de série', 'Volume généreux 320×320×350 mm'],
    cons: ['Machine imposante et lourde (24.5 kg)'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-s1max',
    brand: 'Anycubic',
    name: 'Kobra S1 Max',
    price: 599,
    comboPrice: 799,
    variants: [
      { name: 'Kobra S1 Max (Seule)', price: 599 },
      { name: 'Combo ACE 2 Pro', price: 799 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '350x350x350mm',
    filaments: ['Tous', 'PLA', 'PETG', 'ABS', 'ASA', 'TPU', 'PC', 'PA (Nylon)', 'Composites Carbone/Verre', 'Filaments techniques'],
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé haute résistance',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé renforcé haute température All-Metal',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '36 mm³/s',
    chassis: 'Structure industrielle acier soudé monobloc, isolation thermique et panneaux verre/métal',
    chamberHeating: 'Chauffage passif haute rétention thermique avec gestion intelligente des flux d’air',
    filtration: 'Double filtration HEPA H12 + Charbon actif haute capacité',
    dimensions: '555 × 560 × 660 mm³',
    weight: '29 kg',
    screen: '5" tactile couleur capacitif HD',
    camera: 'Caméra IA HD 1080P intégrée avec Time-lapse et détection d’erreurs',
    sensors: ['Capteur de porte sécurisée', 'Fin de filament', 'Détection d’enchevêtrement', 'Reprise après coupure', 'Capteurs de vibrations doubles'],
    multicolor: { supported: true, system: 'ACE 2 Pro' },
    newTech: 'Format géant CoreXY fermé 350×350×350 mm, Double filtration HEPA + Charbon, Plateau 120°C et buse 320°C',
    pros: ['Volume XXL fermé 350mm pour grands projets techniques', 'Double filtration HEPA & Charbon', 'CoreXY ultra stable 600 mm/s', 'Buse 320°C / Plateau 120°C'],
    cons: ['Poids important (29 kg)', 'Budget haut de gamme'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-kx',
    brand: 'Anycubic',
    name: 'Kobra X',
    price: 299,
    comboPrice: 529,
    variants: [
      { name: '4 couleurs (seule)', price: 299 },
      { name: 'Combo 7 couleurs', price: 529 },
      { name: 'Combo 11 couleurs', price: 748 },
      { name: 'Combo 19 couleurs', price: 1186 }
    ],
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '350x350x350mm',
    filaments: ['Tous', 'PLA', 'PETG', 'ABS', 'ASA', 'TPU', 'Composites'],
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé haute résistance',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé Direct Drive haute adhérence',
    maxSpeed: 500,
    maxAcceleration: '15 000 mm/s²',
    maxFlow: '30 mm³/s',
    chassis: 'Aluminium Extrudé lourd et Acier avec tirants stabilisateurs triangulaires',
    dimensions: '560 × 570 × 650 mm³',
    weight: '19.5 kg',
    screen: '4.3" tactile couleur capacitif',
    camera: 'Caméra HD avec surveillance et time-lapse',
    sensors: ['Multi-capteurs de flux de filament', 'Fin de filament', 'Reprise coupure', 'Nivellement LeviQ 3.0 automatique'],
    multicolor: { supported: true, system: 'Multi-ACE modular (jusqu’à 19 couleurs)' },
    newTech: 'Architecture multi-hub permettant de connecter jusqu’à 5 boîtiers pour 19 couleurs simultanées',
    pros: ['Record du marché jusqu’à 19 couleurs simultanées', 'Grand volume utile 350×350×350 mm', 'Buse 320°C acier trempé'],
    cons: ['Structure ouverte', 'Câblage imposant lors de l’utilisation de multiples boîtiers'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-k4',
    brand: 'Anycubic',
    name: 'Kobra 4',
    price: 199,
    comboPrice: 379,
    variants: [
      { name: 'Kobra 4 (Seule)', price: 199 },
      { name: 'Kobra 4 Combo (ACE Pro Gen 2)', price: 379 }
    ],
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '250x250x260mm',
    filaments: ['Tous', 'PLA', 'PETG', 'TPU', 'ABS', 'ASA'],
    maxNozzleTemp: 320,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé nouvelle génération',
    nozzleDiameter: 0.4,
    extruderGears: 'Acier Trempé (Direct Drive NextGen haute traction)',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '32 mm³/s',
    chassis: 'Aluminium Extrudé aérospatial et Acier usiné',
    dimensions: '455 × 505 × 525 mm³',
    weight: '9.1 kg',
    screen: '4.3" tactile couleur HD',
    camera: 'Caméra HD intégrée avec time-lapse et surveillance distante',
    sensors: ['Fin de filament intelligent', 'Reprise après coupure', 'Capteur de vibration d’axe', 'Calibrage d’offset Z automatique LeviQ 3.0'],
    multicolor: { supported: true, system: 'ACE Pro Gen 2 (en pack combo)' },
    newTech: 'Tête d’extrusion 320°C haute température, ACE Pro Gen 2 à changement de couleur accéléré, LeviQ 3.0',
    pros: ['Super tarif à 199 € seule (au lieu de 379 €)', 'Buse haute température 320°C en acier trempé', 'Séchage actif en version combo', 'Vitesse 600 mm/s'],
    cons: ['Structure ouverte (sensible aux courants d’air)'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },

  // --- PRUSA ---
  {
    id: 'p-oak',
    brand: 'Prusa',
    name: 'Signature Oak',
    price: 3500,
    discontinued: true,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '250x250x250mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'MMU3' },
    newTech: 'Châssis bois chêne massif de collection',
    pros: ['Pièce de collection'],
    cons: ['Modèle discontinué'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'p-ht90',
    brand: 'Prusa',
    name: 'Pro HT90',
    price: 11490,
    enclosed: true,
    structure: 'Delta',
    buildVolume: '300x300x400mm',
    filaments: ['PEEK', 'PEKK', 'PEI', 'PA-CF', 'Industriel'],
    maxNozzleTemp: 500,
    maxBedTemp: 160,
    nozzleType: 'Acier Trempé haute résistance',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Delta ultra-rapide avec chambre chauffée à 90°C',
    pros: ['Matériaux ultra-techniques (PEEK)', 'Chambre chauffée à 90°C', 'Fiabilité industrielle'],
    cons: ['Tarif industriel'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'p-mini',
    brand: 'Prusa',
    name: 'Original Mini +',
    price: 509,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '180x180x180mm',
    filaments: ['PLA', 'PETG', 'ASA'],
    maxNozzleTemp: 280,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Design Cantilever compact',
    pros: ['Robustesse éprouvée', 'Soutien Prusa'],
    cons: ['Petit volume'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'p-mk4s',
    brand: 'Prusa',
    name: 'Original MK4S',
    price: 719,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '250x210x210mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Nextruder High-Flow',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'MMU3 (option)' },
    newTech: 'Nextruder, technologie Perfect Layer, Wi-Fi 360',
    pros: ['Buse Nextruder incroyable', 'Silencieuse', 'Excellente finition'],
    cons: ['Structure ouverte (caisson en option)'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'p-xl',
    brand: 'Prusa',
    name: 'Original XL',
    price: 2299,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '360x360x360mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Nextruder',
    nozzleDiameter: 0.6,
    multicolor: { supported: true, system: 'Toolchanger (1 à 5 têtes)' },
    newTech: 'Vrai changement d\'outils (Toolchanger) sans déchet',
    pros: ['Toolchanger sans purge de fil', 'Grand volume 360mm'],
    cons: ['Encombrante', 'Prix'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'p-coreone',
    brand: 'Prusa',
    name: 'Core One +',
    price: 1049,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '250x250x250mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'MMU3' },
    newTech: 'Boîtier fermé chauffé de conception Prusa CoreXY',
    pros: ['Première vraie Prusa CoreXY fermée', 'Excellente qualité'],
    cons: ['Tarif Prusa'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'p-coreonel',
    brand: 'Prusa',
    name: 'Core One L',
    price: 1849,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '350x350x350mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'MMU3' },
    newTech: 'Format XL fermé avec contrôle thermique avancé',
    pros: ['Grand volume fermé Prusa'],
    cons: ['Investissement conséquent'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },

  // --- ELEGOO ---
  {
    id: 'e-centauri',
    brand: 'Elegoo',
    name: 'Centauri Carbon',
    price: 309,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'TPU', 'PLA-CF', 'ABS', 'ABS-CF', 'ASA', 'ASA-CF', 'PET', 'PET-CF', 'PETG-CF', 'PC', 'PA', 'PPS', 'PPS-CF', 'PPS-GF', 'PPA-CF', 'PPA-GF'],
    maxNozzleTemp: 320,
    maxBedTemp: 110,
    nozzleType: 'Laiton - Acier Trempé haute résistance',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrudeur direct à double engrenage All-Metal (Heatbreak Alliage Titane)',
    maxSpeed: 500,
    maxAcceleration: '20 000 mm/s² (par défaut 10 000 mm/s²)',
    maxFlow: '30 mm³/s',
    chassis: 'Châssis rigide CoreXY fermé en aluminium usiné CNC et parois étanches',
    chamberHeating: 'Chauffage passif régulé avec caisson fermé étanche et porte vitrée',
    filtration: 'Purificateur d’air à cristaux nano-minéraux (Nano Mineral Crystal)',
    dimensions: '398 × 404 × 490 mm³',
    weight: '17.5 kg',
    screen: '4.3" tactile capacitif couleur',
    camera: 'Caméra HD intégrée avec time-lapse et surveillance distante',
    sensors: ['Calibration entièrement automatique (Full-Auto)', 'Auto-nivellement 121 points', 'Fin de filament', 'Déchargement automatique du filament', 'Auto-test ventilateurs (Fan Self-Check)', 'Reprise coupure'],
    multicolor: { supported: false },
    newTech: 'CoreXY fermé haute vitesse avec buse 320 °C, 3 vis mères et 3 barres de guidage sur Z, Bruit silencieux ≤50 dB',
    pros: ['CoreXY fermé très abordable (309 €)', 'Supporte les composites et filaments techniques jusqu’à 320 °C', 'Triple vis Z avec 3 barres de guidage linéaire', 'Nivellement 121 points'],
    cons: ['Monocouleur'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-centauri2',
    brand: 'Elegoo',
    name: 'Centauri Carbon 2',
    price: 339,
    comboPrice: 429,
    variants: [
      { name: 'Centauri Carbon 2 (Seule)', price: 339 },
      { name: 'Centauri Carbon 2 Combo (CANVAS 4 couleurs)', price: 429 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'TPU', 'PLA-CF', 'ABS', 'ABS-CF', 'ASA', 'ASA-CF', 'PET', 'PET-CF', 'PETG-CF', 'PC', 'PA', 'PPS', 'PPS-CF', 'PPS-GF', 'PPA-CF', 'PPA-GF'],
    maxNozzleTemp: 350,
    maxBedTemp: 110,
    nozzleType: 'Laiton - Acier Trempé haute performance 350 °C',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrudeur direct à double engrenage haute adhérence (Heatbreak Alliage Titane)',
    maxSpeed: 500,
    maxAcceleration: '20 000 mm/s² (par défaut 10 000 mm/s²)',
    maxFlow: '32 mm³/s',
    chassis: 'Châssis rigide CoreXY fermé en aluminium usiné CNC haute résistance',
    chamberHeating: 'Chauffage passif régulé avec grille d’échappement intelligente (Smart Exhaust Grille)',
    filtration: 'Purificateur d’air HEPA + Charbon actif de coquille de noix de coco',
    dimensions: '398 × 404 × 490 mm³ (Machine) | 500 × 480 × 743 mm³ (Combo avec CANVAS)',
    weight: '17.5 kg (Machine seule) | 19.35 kg (Pack Combo avec CANVAS)',
    screen: '5" tactile capacitif couleur haute résolution',
    camera: 'Caméra HD intégrée avec time-lapse et surveillance',
    sensors: ['Grille d’échappement intelligente (Smart Exhaust Grille)', 'Détection de bourrage / colmatage (Clog Detection)', 'Détection de chute de ventilateur de refroidissement', 'Auto-nivellement 121 points', 'Fin de filament', 'Déchargement automatique', 'Auto-test ventilateurs', 'Reprise coupure'],
    multicolor: { supported: true, system: 'CANVAS (Système 4 couleurs avec détection RFID et auto-recharge)' },
    newTech: 'Buse haute température 350 °C, Système multicolore CANVAS, Filtration HEPA + Noix de coco, Grille intelligente, Détection de bourrage, Bruit ultra-silencieux ≤45 dB',
    pros: ['Buse poussée à 350 °C pour matériaux industriels (PPA-CF, PPS-CF)', 'Boîtier multicolore CANVAS optionnel', 'Filtration HEPA + Charbon de noix de coco', 'Niveau sonore remarquable ≤45 dB', 'Écran 5" HD et détection de bourrage'],
    cons: ['Prix légèrement supérieur à la V1'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-centauri2open',
    brand: 'Elegoo',
    name: 'Centauri 2',
    price: 299,
    comboPrice: 389,
    variants: [
      { name: 'Centauri 2 (Seule)', price: 299 },
      { name: 'Centauri 2 Combo (CANVAS 4 couleurs)', price: 389 }
    ],
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'PLA-CF', 'TPU'],
    maxNozzleTemp: 350,
    maxBedTemp: 110,
    nozzleType: 'Laiton - Acier Trempé',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrudeur direct à double engrenage (Dual-Gear Direct Extruder)',
    maxSpeed: 500,
    maxAcceleration: '20 000 mm/s² (par défaut 10 000 mm/s²)',
    maxFlow: '30 mm³/s',
    chassis: 'Châssis CoreXY Open Frame en aluminium usiné CNC',
    dimensions: '398 × 404 × 490 mm³ (Machine seule) | 500 × 480 × 586 mm³ (Combo CANVAS)',
    weight: '13.7 kg (Machine seule) | 15.5 kg (Pack Combo avec CANVAS)',
    screen: '5" tactile capacitif couleur',
    sensors: ['Auto-nivellement 121 points', 'Détection de bourrage (Clog Detection)', 'Fin de filament', 'Déchargement automatique', 'Détection de chute de ventilateur', 'Reprise après coupure', 'Auto-test ventilateurs', 'RFID & détection d’emmêlement avec module CANVAS'],
    multicolor: { supported: true, system: 'CANVAS (4 couleurs avec détection RFID, auto-refill et détection d’emmêlement)' },
    newTech: 'CoreXY ouvert ultra-rapide avec écran 5" tactile, Buse 350 °C et compatibilité boîtier multicolore CANVAS 4 couleurs',
    pros: ['CoreXY haute vitesse à moins de 300 €', 'Écran 5" tactile et buse 350 °C', 'Option pack Combo multicolore CANVAS très accessible', 'Triple vis Z avec barres linéaires'],
    cons: ['Structure ouverte (ABS/ASA non recommandés sans caisson)'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-giga',
    brand: 'Elegoo',
    name: 'OrangeStorm Giga',
    price: 2738.97,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '800x800x1000mm',
    filaments: ['PLA', 'PETG', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Buse haute vitesse 0.6 mm (support jusqu’à 4 têtes d’impression)',
    nozzleDiameter: 0.6,
    extruderGears: 'Extrudeur direct haute performance (jusqu’à 4 extrudeurs simultanés)',
    maxSpeed: 300,
    maxAcceleration: '5 000 mm/s²',
    maxFlow: '35 mm³/s',
    chassis: 'Structure industrielle massive en profilés d’aluminium extrudé usiné CNC',
    dimensions: '1 224 × 1 164 × 1 425 mm³',
    weight: '104 kg (Poids net) | 145 kg (Poids brut colis)',
    screen: '7" tactile couleur grande taille',
    sensors: ['Fin de filament', 'Reprise après coupure', 'Nivellement automatique multi-zones', 'Plateau chauffant 4 zones indépendantes de 410×410 mm'],
    multicolor: { supported: false },
    newTech: 'Volume géant de 800×800×1000 mm (0.64 m³), 4 têtes d’impression simultanées possibles, Plateau 4 zones indépendantes de 410×410 mm, Puissance 1530W',
    pros: ['Volume titanesque d’un mètre de hauteur', 'Plateau de 820×820 mm divisé en 4 zones chauffantes indépendantes', 'Capacité multi-têtes jusqu’à 4 pièces en parallèle'],
    cons: ['Poids colossal (104 kg) et encombrement extrême (1.2m de large / 1.4m de haut)', 'Consommation électrique 1530W'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-n4',
    brand: 'Elegoo',
    name: 'Neptune 4',
    price: 189,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '225x225x265mm',
    filaments: ['PLA', 'TPU', 'PETG', 'ABS', 'ASA', 'Nylon'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Buse haute vitesse 300 °C',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrudeur direct à double engrenage (Dual-Gear Direct Drive)',
    maxSpeed: 500,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '24 mm³/s',
    chassis: 'Châssis en aluminium usiné CNC',
    dimensions: '475 × 445 × 515 mm³',
    weight: '8.3 kg',
    screen: '4.3" tactile couleur capacitif amovible',
    sensors: ['Fin de filament', 'Reprise après coupure', 'Nivellement automatique multipoint avec capteur sans contact'],
    multicolor: { supported: false },
    newTech: 'Firmware Klipper préinstallé avec accélération 20 000 mm/s², Grande barre de ventilation auxiliaire avec ventilateurs 5015',
    pros: ['Vitesse 500 mm/s et Klipper natif à moins de 190 €', 'Buse haute température 300 °C compatible Nylon', 'Ventilation auxiliaire très puissante'],
    cons: ['Structure ouverte', 'Niveau sonore de la ventilation'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-n4p',
    brand: 'Elegoo',
    name: 'Neptune 4 Pro',
    price: 219,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '225x225x265mm',
    filaments: ['PLA', 'TPU', 'PETG', 'ABS', 'ASA', 'Nylon'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Buse haute vitesse 300 °C',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrudeur direct à double engrenage All-Metal',
    maxSpeed: 500,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '25 mm³/s',
    chassis: 'Aluminium usiné CNC avec rails de guidage entièrement métalliques en acier sur les axes X et Y',
    dimensions: '475 × 445 × 515 mm³',
    weight: '8.9 kg',
    screen: '4.3" tactile couleur amovible',
    sensors: ['Plateau à double zone de chauffe intelligente (Centre 100W / Extérieur 150W)', 'Fin de filament', 'Reprise après coupure', 'Nivellement automatique multipoint'],
    multicolor: { supported: false },
    newTech: 'Rails de guidage métalliques tout acier sur X et Y, Plateau à double zone de chauffe segmentée pour économie d’énergie, Klipper haute vitesse',
    pros: ['Rails métalliques en acier rigides et durables', 'Plateau chauffant intelligent à double zone', 'Buse 300 °C et vitesse 500 mm/s'],
    cons: ['Ventilation puissante bruyante'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-n4plus',
    brand: 'Elegoo',
    name: 'Neptune 4 Plus',
    price: 339,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '320x320x385mm',
    filaments: ['PLA', 'TPU', 'PETG', 'ABS', 'ASA', 'Nylon'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Buse haute vitesse 300 °C (0.4 mm)',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrudeur direct à double engrenage haute traction',
    maxSpeed: 500,
    maxAcceleration: '12 000 mm/s²',
    maxFlow: '28 mm³/s',
    chassis: 'Aluminium extrudé usiné CNC avec tirants de renfort diagonaux',
    dimensions: '578 × 533 × 640 mm³',
    weight: '14.4 kg',
    screen: '4.3" tactile couleur capacitif',
    sensors: ['Fin de filament', 'Reprise après coupure', 'Nivellement automatique multipoint', 'Wi-Fi intégré', 'Accéléromètre Input Shaping'],
    multicolor: { supported: false },
    newTech: 'Grand volume 320×320×385 mm, Wi-Fi / WLAN intégré avec interface Klipper fluide, Buse 300 °C, Accélération 12 000 mm/s²',
    pros: ['Superbe volume intermédiaire 320mm', 'Wi-Fi natif et contrôle Klipper à distance', 'Vitesse 500 mm/s et tirants de stabilité'],
    cons: ['Encombrement au sol important'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-n4max',
    brand: 'Elegoo',
    name: 'Neptune 4 Max',
    price: 439,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '420x420x480mm',
    filaments: ['PLA', 'TPU', 'PETG', 'ABS', 'ASA', 'Nylon'],
    maxNozzleTemp: 300,
    maxBedTemp: 85,
    nozzleType: 'Buse haute vitesse 300 °C',
    nozzleDiameter: 0.4,
    extruderGears: 'Dual-Gear Direct Drive All-Metal',
    maxSpeed: 500,
    maxAcceleration: '8 000 mm/s²',
    maxFlow: '30 mm³/s',
    chassis: 'Aluminium usiné CNC renforcé avec double axe Z synchronisé et barres stabilisatrices',
    dimensions: '658 × 632 × 740 mm³',
    weight: '18.1 kg',
    screen: '4.3" tactile couleur',
    sensors: ['Fin de filament', 'Reprise coupure', 'Wi-Fi / WLAN', 'Nivellement automatique multipoint haute densité'],
    multicolor: { supported: false },
    newTech: 'Volume géant XXL 420×420×480 mm sous Klipper OS, Module Wi-Fi natif, Barres de renfort triangulaires',
    pros: ['Volume XXL géant à prix imbattable (439 €)', 'Klipper et Wi-Fi intégrés', 'Excellente stabilité grâce aux renforts'],
    cons: ['Plateau limité à 85 °C', 'Châssis très imposant'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-n3p',
    brand: 'Elegoo',
    name: 'Neptune 3 Pro',
    price: 149,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '225x225x280mm',
    filaments: ['PLA', 'TPU', 'PETG', 'ABS', 'ASA'],
    maxNozzleTemp: 260,
    maxBedTemp: 100,
    nozzleType: 'Laiton standard 0.4 mm',
    nozzleDiameter: 0.4,
    extruderGears: 'Extrudeur direct à double engrenage',
    maxSpeed: 180,
    maxAcceleration: '2 500 mm/s²',
    maxFlow: '15 mm³/s',
    chassis: 'Profilés d’aluminium extrudé usiné CNC',
    dimensions: '475 × 445 × 515 mm³',
    weight: '8.1 kg',
    screen: '4.3" tactile couleur amovible avec câble spiralé',
    sensors: ['Fin de filament', 'Reprise après coupure', 'Auto-nivellement multipoint'],
    multicolor: { supported: false },
    newTech: 'Extrudeur direct-drive à double engrenage, Écran tactile détachable, Double vis d’axe Z',
    pros: ['Prix plancher ultra accessible (149 €)', 'Très silencieuse et fiable pour débutants', 'Double vis sans fin sur l’axe Z'],
    cons: ['Vitesse classique 180 mm/s (génération précédente)', 'Température max buse 260 °C'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },

  // --- QIDI TECH ---
  {
    id: 'q-max4',
    brand: 'Qidi Tech',
    name: 'Qidi Max 4',
    price: 1049,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '305x305x300mm',
    filaments: ['Techniques', 'PA-CF', 'PC', 'ABS'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Chambre activement chauffée à 65°C',
    pros: ['Parfaite pour filaments techniques', 'Grande solidité'],
    cons: ['Design massif'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'q-q2',
    brand: 'Qidi Tech',
    name: 'Qidi Q2',
    price: 379,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '200x200x200mm',
    filaments: ['PLA', 'PETG', 'ABS'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Structure cubique fermée compacte',
    pros: ['Fermée et compacte', 'Prix raisonnable'],
    cons: ['Volume 200mm'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'q-q2c',
    brand: 'Qidi Tech',
    name: 'Qidi Q2C',
    price: 379,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '200x200x200mm',
    filaments: ['PLA', 'PETG'],
    maxNozzleTemp: 260,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Cadre CoreXY ouvert',
    pros: ['Châssis rigide'],
    cons: ['Ouverte'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'q-q1pro',
    brand: 'Qidi Tech',
    name: 'Q1 Pro 3D',
    price: 549,
    discontinued: true,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '245x245x245mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'AI Cam, Klipper OS',
    pros: ['Chambre chauffée'],
    cons: ['Ancien modèle discontinué'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'q-plus4',
    brand: 'Qidi Tech',
    name: 'Qidi Plus 4',
    price: 699,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '280x280x280mm',
    filaments: ['Tous', 'Carbone'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Chambre chauffée 65°C, buse 350°C',
    pros: ['Excellents résultats sur ABS/ASA/PC'],
    cons: ['Pas de multicolore natif'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'q-plus5',
    brand: 'Qidi Tech',
    name: 'Qidi Plus 5',
    price: 749,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '300x300x300mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Chambre régulée thermique, nouveau moteur direct drive',
    pros: ['Grand volume fermé 300mm', 'Impression haute température'],
    cons: ['Assez lourde'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'q-xmax3',
    brand: 'Qidi Tech',
    name: 'X-Max 3',
    price: 899,
    discontinued: true,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '325x325x315mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'CoreXY Industrial Grade',
    pros: ['Grand volume'],
    cons: ['Modèle discontinué'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },

  // --- FLASHFORGE ---
  {
    id: 'f-guider3u',
    brand: 'Flashforge',
    name: 'Guider 3 Ultra',
    price: 3499,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '330x330x600mm',
    filaments: ['Tous', 'ABS', 'ASA', 'PC', 'PA-CF', 'PETG-CF'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé haute résistance',
    nozzleDiameter: 0.4,
    extruderGears: 'Double extrudeur Direct Drive haute température',
    maxSpeed: 500,
    maxAcceleration: '20 000 mm/s²',
    chassis: 'Structure fermée industrielle ultra rigide en acier soudé',
    chamberHeating: 'Chauffage passif régulé avec chambre isolée étanche',
    filtration: 'Système de filtration d’air à double filtre HEPA + charbon actif',
    dimensions: '635 × 550 × 1070 mm³',
    weight: '70 kg',
    screen: '7" tactile couleur capacitif',
    camera: 'Caméra HD intégrée avec time-lapse',
    sensors: ['Double extrudeur avec nivellement automatique', 'Fin de filament', 'Reprise après coupure', 'Refroidissement actif'],
    multicolor: { supported: true, system: 'Double Extrudeur Indépendant' },
    newTech: 'Volume vertical record de 600 mm, Double extrudeur, Filtration HEPA et vitesse 500 mm/s',
    pros: ['Volume vertical immense de 600 mm', 'Double extrudeur pour supports solubles et bi-matières', 'Buse haute température 350 °C'],
    cons: ['Poids colossal (70 kg)', 'Tarif industriel'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'f-a5mpro',
    brand: 'Flashforge',
    name: 'Adventurer 5M Pro',
    price: 449,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '220x220x220mm',
    filaments: ['PLA', 'PETG', 'ABS', 'ASA', 'TPU', 'PLA-CF', 'PETG-CF'],
    maxNozzleTemp: 280,
    maxBedTemp: 100,
    nozzleType: 'Buse à démontage rapide 3s (0.4 mm inclus, options 0.25 / 0.6 / 0.8 mm)',
    nozzleDiameter: 0.4,
    extruderGears: 'Direct Drive All-Metal haute performance',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '32 mm³/s',
    chassis: 'Conception de cadre fermé insonorisé avec porte vitrée',
    chamberHeating: 'Chauffage passif régulé avec double circulation',
    filtration: 'Circulation interne + circulation externe (HEPA + charbon actif)',
    dimensions: '380 × 400 × 453 mm³ (sans porte-bobine)',
    weight: '14.5 kg',
    screen: '4.3" tactile couleur',
    camera: 'Caméra HD intégrée avec surveillance à distance et Time-lapse',
    sensors: ['Surveillance par caméra', 'Alerte de fin de filament', 'Arrêt automatique', 'Reprise après coupure de courant', 'Mode faible bruit 50 dB', 'Compensation des vibrations'],
    multicolor: { supported: false },
    newTech: 'Double filtration HEPA + charbon actif interne/externe, Mode silencieux 50 dB, Buse démontage rapide en 3 secondes, Vitesse 600 mm/s, Arrêt automatique',
    pros: ['Double filtration d’air HEPA + charbon actif pour intérieur', 'Mode ultra silencieux à 50 dB', 'Buse clipsable interchangeable en 3 secondes', 'Caméra HD et arrêt automatique intégrés'],
    cons: ['Volume compact de 220×220×220 mm', 'Impression monocouleur'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'f-a5m',
    brand: 'Flashforge',
    name: 'Adventurer 5M',
    price: 279,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '220x220x220mm',
    filaments: ['PLA', 'PETG', 'TPU', 'PLA-CF', 'PETG-CF'],
    maxNozzleTemp: 280,
    maxBedTemp: 100,
    nozzleType: 'Buse à démontage rapide 3s (0.4 mm inclus, options 0.25 / 0.6 / 0.8 mm)',
    nozzleDiameter: 0.4,
    extruderGears: 'Direct Drive All-Metal',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '32 mm³/s',
    chassis: 'Conception à cadre ouvert CoreXY rigide',
    dimensions: '363 × 376 × 413 mm³ (hors écran) / 363 × 402 × 448 mm³ (avec écran)',
    weight: '10.8 kg',
    screen: '4.3" tactile couleur',
    sensors: ['Alerte de fin de filament', 'Récupération après coupure de courant', 'Auto-nivellement en 1 clic sans feuille', 'Compensation des vibrations'],
    multicolor: { supported: false },
    newTech: 'CoreXY 600 mm/s ultra accessible, Auto-nivellement complet en 1 clic, Buse interchangeable en 3 secondes',
    pros: ['Vitesse déplacement 600 mm/s sous les 280 €', 'Auto-nivellement sans feuille en un clic', 'Changement de buse instantané sans outil', 'Écran 4.3" tactile réactif'],
    cons: ['Structure ouverte (ABS/ASA déconseillés sans caisson)', 'Pas de caméra intégrée de série'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'f-ad5x',
    brand: 'Flashforge',
    name: 'AD5X',
    price: 349,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '220x220x220mm',
    filaments: ['PETG', 'PLA', 'TPU95A', 'TPU64D-75D', 'PLA-CF', 'PETG-CF'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Buse haute température 300 °C (0.4 mm standard, options 0.25 / 0.6 / 0.8 mm)',
    nozzleDiameter: 0.4,
    extruderGears: 'Direct Drive All-Metal haute adhérence',
    maxSpeed: 600,
    maxAcceleration: '20 000 mm/s²',
    maxFlow: '30 mm³/s',
    chassis: 'Châssis CoreXY en profilés aluminium et acier haute rigidité',
    dimensions: '363 × 376 × 413 mm³',
    weight: '11.2 kg',
    screen: '4.3" tactile couleur',
    sensors: ['Détection de filament', 'Rétablissement du courant', 'Mise à niveau automatique', 'Gestion multi-appareils (Ferme)', 'Éclairage et caméra extensibles'],
    multicolor: { supported: false },
    newTech: 'Buse haute température 300 °C, Vitesse déplacement 600 mm/s (impression 300 mm/s), Gestion multi-appareils pour fermes d’impression',
    pros: ['Buse poussée à 300 °C compatible TPU techniques et filaments carbone', 'Gestion multi-appareils native pour fermes d’impression', 'Vitesse 600 mm/s et accélération 20 000 mm/s²'],
    cons: ['Structure ouverte d’origine', 'Caméra et éclairage en options extensibles'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'f-c5',
    brand: 'Flashforge',
    name: 'Creator 5',
    price: 849,
    enclosed: false,
    structure: 'IDEX',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'TPU', 'PLA-CF', 'PETG-CF', 'Soie', 'PVA', 'BVOH', 'ABS', 'ASA', 'HIPS', 'PA-CF', 'PET-CF', 'PAHT-CF', 'PPA-CF', 'PPS-CF'],
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    nozzleType: 'Buse amovible démontage rapide (0.4 mm standard, options 0.25 / 0.6 / 0.8 mm)',
    nozzleDiameter: 0.4,
    extruderGears: '4 têtes d’outils indépendantes (Quad Toolheads) Direct Drive haute précision',
    maxSpeed: 600,
    maxAcceleration: '30 000 mm/s²',
    maxFlow: '32 mm³/s',
    chassis: 'Conception à cadre ouvert (Open Frame) rigide haute résistance',
    dimensions: '520 × 443 × 710 mm³ (avec supports) / 436 × 432 × 480 mm³ (sans supports)',
    weight: '14 kg (Net) | 18 kg (Brut)',
    screen: '4" tactile couleur 800 × 480',
    camera: 'Caméra Full HD intégrée (1280×720 à 30 fps) avec surveillance à distance',
    sensors: ['4 têtes d’outils indépendantes avec détection fin de filament', 'Étalonnage dynamique du débit (Calibrage automatique PA)', 'Mise à niveau automatique complète', 'Rétablissement du courant', 'Éclairage de chambre', 'Gestion de plusieurs imprimantes', 'Allumage/extinction en une seule touche'],
    multicolor: { supported: true, system: '4 Têtes d’outils indépendantes (Quad Toolheads sans tour de purge)' },
    newTech: '4 têtes d’outils indépendantes sans aucune perte de filament, Calibrage automatique PA, Accélération extrême 30 000 mm/s², Buse 320 °C, Wi-Fi 2.4/5 GHz',
    pros: ['4 têtes d’outils indépendantes pour imprimer en multi-matériaux sans tour de purge ni gaspillage', 'Accélération phénoménale de 30 000 mm/s² et débit de 32 mm³/s', 'Buse haute température 320 °C et plateau 120 °C', 'Caméra Full HD et gestion multi-machines intégrées'],
    cons: ['Conception à cadre ouvert (nécessite un kit caisson pour ABS/PA-CF)', 'Largeur importante avec les 4 dévidoirs de filaments'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'f-c5pro',
    brand: 'Flashforge',
    name: 'Creator 5 Pro',
    price: 1199,
    enclosed: true,
    structure: 'IDEX',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'TPU', 'PLA-CF', 'PETG-CF', 'PET', 'Soie', 'PVA', 'BVOH', 'ABS', 'ASA', 'PA-CF', 'PET-CF', 'PAHT-CF', 'PC', 'PA', 'PC-ABS', 'PPS-CF', 'PPA-CF'],
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    nozzleType: 'Buse amovible démontage rapide (0.4 mm standard, options 0.25 / 0.6 / 0.8 mm)',
    nozzleDiameter: 0.4,
    extruderGears: '4 têtes d’outils indépendantes (Quad Toolheads) Direct Drive haute température',
    maxSpeed: 600,
    maxAcceleration: '30 000 mm/s²',
    maxFlow: '32 mm³/s',
    chassis: 'Conception de cadre fermé avec isolation thermique intégrale et portes vitrées',
    chamberHeating: 'Chauffage actif de la chambre supporté (Max 65 °C)',
    filtration: 'Filtre HEPA13 + charbon actif haute efficacité',
    dimensions: '520 × 443 × 710 mm³ (avec supports) / 441 × 411 × 460 mm³ (sans supports)',
    weight: '18 kg (Net) | 22 kg (Brut)',
    screen: '4" tactile couleur 800 × 480',
    camera: 'Caméra Full HD intégrée (1280×720 à 30 fps) avec surveillance à distance',
    sensors: ['4 têtes d’outils indépendantes avec capteurs de filament', 'Chambre activement chauffée à 65 °C', 'Filtre HEPA 13 + charbon actif', 'Détection de porte (porte avant et couvercle supérieur)', 'Ventilateur de refroidissement auxiliaire', 'Étalonnage dynamique du débit (Calibrage PA)', 'Mise à niveau automatique', 'Rétablissement du courant', 'Éclairage de chambre', 'Allumage en une seule touche'],
    multicolor: { supported: true, system: '4 Têtes d’outils indépendantes (Quad Toolheads sans tour de purge)' },
    newTech: '4 têtes d’outils indépendantes en caisson fermé, Chambre activement chauffée à 65 °C, Filtre HEPA 13 + charbon actif, Détection de porte, Buse 320 °C, Accélération 30 000 mm/s²',
    pros: ['4 têtes d’impression indépendantes sous caisson clos sans aucun déchet de purge', 'Chambre activement chauffée jusqu’à 65 °C pour plastiques industriels (PC, Nylon, PPS-CF)', 'Double filtration HEPA 13 + charbon actif et refroidissement auxiliaire', 'Capteur de porte sécurisée et accélération 30 000 mm/s²'],
    cons: ['Poids important de 18 kg', 'Consommation électrique de 850W'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },

  // --- SOVOL ---
  {
    id: 's-sv08max',
    brand: 'Sovol',
    name: 'SV08 Max',
    price: 939,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '450x450x450mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Style Voron 2.4 CoreXY XL 450mm',
    pros: ['Volume Voron open source géant'],
    cons: ['Taille de la machine'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 's-sv08',
    brand: 'Sovol',
    name: 'SV08',
    price: 469,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '350x350x350mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Inspirée de Voron 2.4 open-source',
    pros: ['CoreXY 350mm très rapide', 'Excellente communauté open-source'],
    cons: ['Modèle ouvert'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 's-sv06lace',
    brand: 'Sovol',
    name: 'SV06 Plus ACE',
    price: 254,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '300x300x340mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'ACE System' },
    newTech: 'Volume 300mm compatible système couleur ACE',
    pros: ['Prix compétitif', 'Grand volume'],
    cons: ['Structure cartésienne classique'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 's-sv06ace',
    brand: 'Sovol',
    name: 'SV06 ACE',
    price: 209,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'PETG', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Direct drive haute précision',
    pros: ['Super rapport qualité/prix à 209€'],
    cons: ['Ouverte'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 's-zero',
    brand: 'Sovol',
    name: 'Sovol Zero',
    price: 359,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '180x180x180mm',
    filaments: ['PLA', 'PETG', 'ABS'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'CoreXY ultra-compacte style Voron V0',
    pros: ['Ultra rapide et compacte'],
    cons: ['Petit volume'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },

  // --- SNAPMAKER ---
  {
    id: 'sm-u1',
    brand: 'Snapmaker',
    name: 'Snapmaker U1',
    price: 899,
    enclosed: false,
    structure: 'IDEX',
    buildVolume: '270x270x270mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'IDEX Double Tête' },
    newTech: 'Independant Dual Extruder (IDEX) pour 2 couleurs/matériaux sans purge',
    pros: ['Impression bicolore/support soluble rapide', 'Zéro déchet de purge'],
    cons: ['Cadre ouvert'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'sm-artisan-prem',
    brand: 'Snapmaker',
    name: 'Artisan Premium 3-in-1',
    price: 2699,
    enclosed: true,
    structure: 'Cartésienne XYZ',
    buildVolume: '400x400x400mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'Dual Extruder Module' },
    newTech: 'Machine 3-en-1 : Impression 3D 400°C, Gravure Laser 40W, Fraisage CNC 200W',
    pros: ['Atelier complet 3D + Laser 40W + CNC', 'Boîtier fermé géant', 'Qualité industrielle'],
    cons: ['Tarif pro'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'sm-artisan',
    brand: 'Snapmaker',
    name: 'Artisan 3-in-1',
    price: 2299,
    enclosed: true,
    structure: 'Cartésienne XYZ',
    buildVolume: '400x400x400mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'Dual Extruder Module' },
    newTech: 'Machine 3-en-1 : Impression 3D, Gravure Laser 10W, Fraisage CNC 200W',
    pros: ['Plateau géant 400mm', 'Modules interchangeables en 1 min'],
    cons: ['Poids important'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  }
];

export const allRequestedPrinters: Printer[] = [...printers];

export const filaments: FilamentType[] = [
  { name: 'PLA', description: 'Le plus populaire, biodégradable et facile.', pros: ['Facile à imprimer', 'Pas d\'odeur', 'Précision'], cons: ['Fragile à la chaleur', 'Pas très solide'], difficulty: 1 },
  { name: 'PETG', description: 'Le juste milieu entre PLA et ABS.', pros: ['Solide', 'Résistant aux UV', 'Durable'], cons: ['Fils d\'ange (stringing)', 'Adhère trop'], difficulty: 2 },
  { name: 'PET', description: 'Version pure du PETG, souvent translucide.', pros: ['Recyclable', 'Clarté optique'], cons: ['Difficile à dompter'], difficulty: 3 },
  { name: 'ABS', description: 'Plastique industriel standard.', pros: ['Solide', 'Résiste à la chaleur', 'Lissable'], cons: ['Odeurs', 'Warping'], difficulty: 4 },
  { name: 'ASA', description: 'Le successeur de l\'ABS, résistant aux UV.', pros: ['Tenue extérieure parfaite', 'Mécanique'], cons: ['Warping'], difficulty: 4 },
  { name: 'TPU', description: 'Matériau flexible type caoutchouc.', pros: ['Incassable', 'Flexible'], cons: ['Très lent', 'Bouchage possible'], difficulty: 3 },
  { name: 'Nylon', description: 'Extrêmement solide et résistant à l\'usure.', pros: ['Durable', 'Faible friction'], cons: ['Hygroscopique', 'Warping'], difficulty: 5 },
  { name: 'PC', description: 'Polycarbonate pour une solidité maximale.', pros: ['Ultra résistant', 'Température'], cons: ['Très difficile'], difficulty: 5 },
  { name: 'PPS', description: 'Polymère haute performance industrielle.', pros: ['Chimiquement inerte', 'Stable'], cons: ['Prix industriel'], difficulty: 5 }
];

export const filamentBrands: FilamentBrand[] = [
  { name: 'Elegoo', pros: ['Prix imbattable', 'Fiabilité'], cons: ['Peu de couleurs'] },
  { name: 'Anycubic', pros: ['Accessible', 'Standard'], cons: ['Cassant'] },
  { name: 'Bambu Lab', pros: ['RFID', 'Enroulement', 'Qualité'], cons: ['Prix', 'Propriétaire'] },
  { name: 'Creality', pros: ['Standard', 'Pas cher'], cons: ['Qualité variable'] },
  { name: 'eSUN', pros: ['PLA+ reconnu', 'Choix'], cons: ['Bobines plastiques'] },
  { name: 'Prusament', pros: ['Précision ±0.02', 'Traçabilité'], cons: ['Cher'] },
  { name: 'Polymaker', pros: ['Technique', 'PolyTerra'], cons: ['Premium'] },
  { name: 'Rosa3D', pros: ['Couleurs Silk', 'Europe'], cons: ['Sourcing'] },
  { name: 'Sunlu', pros: ['Pas cher', 'Test'], cons: ['Enroulement'] },
  { name: 'GST 3D', pros: ['Kilo pas cher'], cons: ['Qualité'] },
  { name: 'Recreus', pros: ['Leader TPU'], cons: ['Cher'] },
  { name: 'Formfutura', pros: ['Exotique'], cons: ['Prix'] },
  { name: 'Overture', pros: ['Fiable', 'Tapis inclus'], cons: ['Basique'] }
];
