import { Printer, FilamentType, FilamentBrand } from './types';

export const printers: Printer[] = [
  // --- BAMBU LAB ---
  {
    id: 'b-a1mini',
    brand: 'Bambu Lab',
    name: 'A1 Mini',
    price: 189,
    comboPrice: 299,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '180x180x180mm',
    filaments: ['PLA', 'PETG', 'TPU', 'PVA'],
    maxNozzleTemp: 300,
    maxBedTemp: 80,
    nozzleType: 'Acier Inoxydable',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'AMS Lite' },
    newTech: 'Active Flow Rate Compensation, Silencieuse',
    pros: ['Plug & Play', 'Très silencieuse', 'Qualité irréprochable'],
    cons: ['Petit volume (180mm)', 'Chassis ouvert'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'b-a1',
    brand: 'Bambu Lab',
    name: 'A1',
    price: 259,
    comboPrice: 369,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'TPU', 'PVA'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Inoxydable',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'AMS Lite' },
    newTech: 'Buse changement rapide, Active Noise Cancellation',
    pros: ['Vitesse impressionnante', 'Changement de buse ultra-rapide', 'Polyvalente'],
    cons: ['Non fermée (ABS/ASA difficiles)'],
    image: 'https://images.unsplash.com/photo-1701162444317-036f32e2d097?q=80&w=800'
  },
  {
    id: 'b-a2l',
    brand: 'Bambu Lab',
    name: 'A2L',
    price: 379,
    comboPrice: 489,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'TPU', 'PVA'],
    maxNozzleTemp: 320,
    maxBedTemp: 100,
    nozzleType: 'Acier Inoxydable',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'AMS Lite Gen 2' },
    newTech: 'Capteur de débit optique v2, nivellement auto laser',
    pros: ['Nouveau standard grand public', 'Multicolore encore plus rapide'],
    cons: ['Pas de caisson chauffé'],
    image: 'https://images.unsplash.com/photo-1701162444317-036f32e2d097?q=80&w=800'
  },
  {
    id: 'b-p1p',
    brand: 'Bambu Lab',
    name: 'P1P',
    price: 499,
    discontinued: true,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Inoxydable',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'AMS' },
    newTech: 'CoreXY Haute Vitesse',
    pros: ['Ancien classique très rapide'],
    cons: ['Modèle discontinué', 'Pas de caisson'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'b-p1s',
    brand: 'Bambu Lab',
    name: 'P1S',
    price: 379,
    comboPrice: 529,
    variants: [
      { name: 'Sans Combo', price: 379 },
      { name: 'Combo AMS classique', price: 529 },
      { name: 'Combo AMS 2 (Nouvel AMS)', price: 549 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG', 'ABS', 'ASA', 'PA', 'PC'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Inoxydable',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'AMS / AMS 2' },
    newTech: 'Chambre fermée filtrée, CoreXY haute performance',
    pros: ['Rapport qualité/prix imbattable', 'Boîtier fermé', 'Très grande communauté'],
    cons: ['Écran monochrome d\'origine'],
    image: 'https://images.unsplash.com/photo-1701162444265-d018721c4b22?q=80&w=800'
  },
  {
    id: 'b-p2s',
    brand: 'Bambu Lab',
    name: 'P2S',
    price: 519,
    comboPrice: 699,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['Tous'],
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'AMS 2.0' },
    newTech: 'Chambre chauffée activement, moteur pas-à-pas silencieux v2',
    pros: ['Écran tactile HD', 'Boîtier fermé', 'Précision extrême'],
    cons: ['Prix supérieur au P1S'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'b-h2d',
    brand: 'Bambu Lab',
    name: 'H2D',
    price: 1549,
    comboPrice: 1749,
    variants: [
      { name: 'Seule', price: 1549 },
      { name: 'Combo AMS', price: 1749 },
      { name: 'Combo + Laser 10W', price: 2149 },
      { name: 'Combo + Laser 40W', price: 2549 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '300x300x300mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'Vortex' },
    newTech: 'Double buses indépendantes, extension Laser',
    pros: ['Buse double', 'Grand volume 300mm', 'Option gravure laser'],
    cons: ['Budget imposant'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'b-h2s',
    brand: 'Bambu Lab',
    name: 'H2S',
    price: 1099,
    comboPrice: 1299,
    variants: [
      { name: 'Seule', price: 1099 },
      { name: 'Combo AMS', price: 1299 },
      { name: 'Combo + Laser', price: 1699 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '300x300x300mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'Vortex' },
    newTech: 'Auto-Switch Nozzles, Vortex cooling',
    pros: ['Chambre fermée', 'Productivité', 'Grand volume'],
    cons: ['Machine imposante'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'b-h2c',
    brand: 'Bambu Lab',
    name: 'H2C',
    price: 2149,
    comboPrice: 2149,
    variants: [
      { name: 'Combo obligatoire', price: 2149 },
      { name: 'Combo + Laser 10W', price: 2549 },
      { name: 'Combo + Laser 40W', price: 2949 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '300x300x300mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'Vortex Pro' },
    newTech: 'Triple/Quad buses, Vortex cooling, Module Laser optionnel',
    pros: ['Sommet de gamme', 'Multicolore ultra rapide sans purge', 'Pro'],
    cons: ['Prix très élevé'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'b-x1c',
    brand: 'Bambu Lab',
    name: 'X1C (X1-Carbon)',
    price: 1199,
    discontinued: true,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'AMS' },
    newTech: 'AI Lidar, Détection spaghettis',
    pros: ['Pionnière des imprimantes IA'],
    cons: ['Modèle discontinué (remplacé par X2D / P2S)'],
    image: 'https://images.unsplash.com/photo-1701162444317-036f32e2d097?q=80&w=800'
  },
  {
    id: 'b-x2d',
    brand: 'Bambu Lab',
    name: 'X2D',
    price: 629,
    comboPrice: 849,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['Tous'],
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'AMS Gen 2' },
    newTech: 'AI Lidar 2.0, Active Noise Cancellation Pro, Caméra dual',
    pros: ['Boîtier fermé très robuste', 'Intelligence Artificielle', 'Silencieuse'],
    cons: ['Tarif premium'],
    image: 'https://images.unsplash.com/photo-1701162444317-036f32e2d097?q=80&w=800'
  },

  // --- CREALITY ---
  {
    id: 'c-i7',
    brand: 'Creality',
    name: 'i7 Color Combo',
    price: 259,
    comboPrice: 339,
    variants: [
      { name: 'Seule', price: 259 },
      { name: 'Combo CFS Nano', price: 299 },
      { name: 'Combo Autofill', price: 309 },
      { name: 'Combo CFS Lite Color', price: 339 }
    ],
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '250x250x250mm',
    filaments: ['PLA', 'PETG', 'ABS'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'CFS Lite / Nano' },
    newTech: 'Châssis compact coloré, système CFS Lite',
    pros: ['Prix multicolore d\'entrée de gamme', 'Légère'],
    cons: ['Structure ouverte'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'c-k2',
    brand: 'Creality',
    name: 'K2',
    price: 359,
    comboPrice: 499,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '300x300x300mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'CFS' },
    newTech: 'Chambre chauffée active, système de couleur CFS',
    pros: ['Grande vitesse', 'Boîtier fermé', 'CFS compatible'],
    cons: ['Ventilation sonore'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k2se',
    brand: 'Creality',
    name: 'K2 SE',
    price: 289,
    comboPrice: 399,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '250x250x250mm',
    filaments: ['PLA', 'PETG', 'ABS', 'ASA'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'CFS Compatible' },
    newTech: 'Klipper CoreXY Optimization',
    pros: ['CoreXY très abordable', 'Compatible CFS'],
    cons: ['Cadre semi-ouvert'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-e3v4combo',
    brand: 'Creality',
    name: 'Ender-3 V4 Combo',
    price: 369,
    comboPrice: 369,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'PETG', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'Mini-CFS (inclus)' },
    newTech: 'Ender de 4ème génération avec Mini-CFS intégré',
    pros: ['Impression multicolore accessible', 'Améliorations V4'],
    cons: ['Combo obligatoire (sans combo n\'existe pas)'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k2pro',
    brand: 'Creality',
    name: 'K2 Pro',
    price: 549,
    comboPrice: 749,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '300x300x300mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'CFS' },
    newTech: 'Active Heated Chamber + AI Dual Camera',
    pros: ['Très solide', 'Boîtier fermé chauffé', 'Haute température'],
    cons: ['Poids élevé'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k2plus',
    brand: 'Creality',
    name: 'K2 Plus',
    price: 999,
    comboPrice: 1249,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '350x350x350mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'CFS' },
    newTech: 'Chambre chauffée XL, moteurs servo boucle fermée',
    pros: ['Volume XL 350mm', 'Boîtier entièrement fermé', 'Précision pro'],
    cons: ['Encombrement important'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k1max',
    brand: 'Creality',
    name: 'K1 Max',
    price: 499,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '300x300x300mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'AI Camera, Lidar, CoreXY 600mm/s',
    pros: ['Grand volume fermé', 'Baisse de prix attractive', 'Très rapide'],
    cons: ['Monocouleur'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k1c',
    brand: 'Creality',
    name: 'K1C',
    price: 349,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'ABS', 'Carbon', 'PETG'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Buse anti-bouchage bimétal, Caméra IA',
    pros: ['Boîtier fermé compact', 'Buse carbone prête'],
    cons: ['Volume standard'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k1',
    brand: 'Creality',
    name: 'K1',
    price: 299,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'PETG', 'ABS'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'CoreXY 600mm/s classique',
    pros: ['Fermée à moins de 300€', 'Rapide'],
    cons: ['Première révision de la série K'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-k1se',
    brand: 'Creality',
    name: 'K1 SE',
    price: 279,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'PETG'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'CoreXY Open Frame ultra rapide',
    pros: ['Ultra rapide', 'Prix plancher CoreXY'],
    cons: ['Non fermée'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-hi',
    brand: 'Creality',
    name: 'Hi Combo',
    price: 259,
    comboPrice: 259,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '200x200x200mm',
    filaments: ['PLA', 'PETG'],
    maxNozzleTemp: 260,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'Hi-Color' },
    newTech: 'Design compact pour jeunes créateurs',
    pros: ['Facile à transporter', 'Ludique'],
    cons: ['Petit volume'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-v3ke',
    brand: 'Creality',
    name: 'Ender-3 V3 KE',
    price: 239,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '220x220x240mm',
    filaments: ['PLA', 'ABS', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Klipper OS intégré, Rail linéaire X',
    pros: ['Très rapide (500mm/s)', 'Klipper simple'],
    cons: ['Structure ouverte'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-v3',
    brand: 'Creality',
    name: 'Ender-3 V3 (Original)',
    price: 329,
    discontinued: true,
    enclosed: false,
    structure: 'CoreXZ',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'ABS', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'CoreXZ Motion',
    pros: ['Bonne stabilité'],
    cons: ['Modèle discontinué'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-v3se',
    brand: 'Creality',
    name: 'Ender-3 V3 SE',
    price: 169,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'PETG'],
    maxNozzleTemp: 250,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Nivellement automatique Strain Gauge',
    pros: ['Prix mini (169€)', 'Très simple pour débutants'],
    cons: ['Structure ouverte', 'Non adaptée ABS'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-v3plus',
    brand: 'Creality',
    name: 'Ender-3 V3 Plus',
    price: 399,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '300x300x330mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Châssis double tige de renfort',
    pros: ['Grand volume 300mm pas cher'],
    cons: ['Machine ouverte imposante'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 'c-e5max',
    brand: 'Creality',
    name: 'Ender-5 Max',
    price: 799,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '350x350x400mm',
    filaments: ['PLA', 'ABS'],
    maxNozzleTemp: 260,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Structure cubique haute stabilité',
    pros: ['Très grand volume cubique'],
    cons: ['Encombrement'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },

  // --- ANYCUBIC ---
  {
    id: 'a-k2max',
    brand: 'Anycubic',
    name: 'Kobra 2 Max',
    price: 499,
    discontinued: true,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '420x420x500mm',
    filaments: ['PLA', 'PETG'],
    maxNozzleTemp: 260,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Vitesse 500mm/s grand format',
    pros: ['Volume géant'],
    cons: ['Modèle discontinué (remplacé par Kobra 3 Max)'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-k3',
    brand: 'Anycubic',
    name: 'Kobra 3 Combo',
    price: 379,
    comboPrice: 379,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '250x250x260mm',
    filaments: ['PLA', 'PETG'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'ACE Pro (inclus)' },
    newTech: 'ACE Pro avec séchage actif des filaments',
    pros: ['Multicolore avec séchage intégré', 'Excellent tarif'],
    cons: ['Non fermée'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-k3v2',
    brand: 'Anycubic',
    name: 'Kobra 3 V2 Combo',
    price: 329,
    comboPrice: 329,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '250x250x260mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'ACE Pro (inclus)' },
    newTech: 'ACE Pro v2, Nivellement amélioré',
    pros: ['Prix réduit', 'Nivellement ultra réactif'],
    cons: ['Châssis ouvert'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-k3max',
    brand: 'Anycubic',
    name: 'Kobra 3 Max',
    price: 429,
    comboPrice: 499,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '420x420x450mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'ACE Pro' },
    newTech: 'Multicolore géant 420mm',
    pros: ['Très grand volume + multicolore'],
    cons: ['Incombrante'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-s1',
    brand: 'Anycubic',
    name: 'Kobra S1 Combo',
    price: 399,
    comboPrice: 399,
    variants: [
      { name: 'Combo ACE Pro', price: 399 },
      { name: 'Combo ACE 2 Pro', price: 499 }
    ],
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '320x320x350mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'ACE 2 Pro' },
    newTech: 'Chambre fermée CoreXY 320mm, ACE 2 Pro',
    pros: ['Grande taille fermée', 'Multicolore performant'],
    cons: ['Nécessite de l\'espace'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-s1max',
    brand: 'Anycubic',
    name: 'Kobra S1 Max',
    price: 599,
    comboPrice: 799,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '350x350x350mm',
    filaments: ['Tous'],
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'ACE 2 Pro' },
    newTech: 'Format géant fermé avec ACE 2 Pro',
    pros: ['Volume XL fermé', 'Impression multi-matériaux'],
    cons: ['Budget élevé'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-kx',
    brand: 'Anycubic',
    name: 'Kobra X',
    price: 299,
    comboPrice: 529,
    variants: [
      { name: '4 couleurs (seule)', price: 299 },
      { name: 'Combo 7 couleurs', price: 529 },
      { name: 'Combo 11 couleurs', price: 748 },
      { name: 'Combo 19 couleurs', price: 1186 }
    ],
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '350x350x350mm',
    filaments: ['Tous'],
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'Multi-ACE modular (jusqu\'à 19 couleurs)' },
    newTech: 'Extension modulaire jusqu\'à 19 couleurs simultanées',
    pros: ['Capacité jusqu\'à 19 couleurs', 'Grand volume'],
    cons: ['Structure ouverte'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'a-k4combo',
    brand: 'Anycubic',
    name: 'Kobra 4 Combo',
    price: 279,
    comboPrice: 379,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '250x250x260mm',
    filaments: ['Tous'],
    maxNozzleTemp: 320,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'ACE Pro Gen 2' },
    newTech: 'NextGen ACE Pro, changement de couleur rapide',
    pros: ['Buses haute résistance', 'Séchage actif'],
    cons: ['Non fermée'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },

  // --- PRUSA ---
  {
    id: 'p-oak',
    brand: 'Prusa',
    name: 'Signature Oak',
    price: 3500,
    discontinued: true,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '250x250x250mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'MMU3' },
    newTech: 'Châssis bois chêne massif de collection',
    pros: ['Pièce de collection'],
    cons: ['Modèle discontinué'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'p-ht90',
    brand: 'Prusa',
    name: 'Pro HT90',
    price: 11490,
    enclosed: true,
    structure: 'Delta',
    buildVolume: '300x300x400mm',
    filaments: ['PEEK', 'PEKK', 'PEI', 'PA-CF', 'Industriel'],
    maxNozzleTemp: 500,
    maxBedTemp: 160,
    nozzleType: 'Acier Trempé haute résistance',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Delta ultra-rapide avec chambre chauffée à 90°C',
    pros: ['Matériaux ultra-techniques (PEEK)', 'Chambre chauffée à 90°C', 'Fiabilité industrielle'],
    cons: ['Tarif industriel'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'p-mini',
    brand: 'Prusa',
    name: 'Original Mini +',
    price: 509,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '180x180x180mm',
    filaments: ['PLA', 'PETG', 'ASA'],
    maxNozzleTemp: 280,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Design Cantilever compact',
    pros: ['Robustesse éprouvée', 'Soutien Prusa'],
    cons: ['Petit volume'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'p-mk4s',
    brand: 'Prusa',
    name: 'Original MK4S',
    price: 719,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '250x210x210mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Nextruder High-Flow',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'MMU3 (option)' },
    newTech: 'Nextruder, technologie Perfect Layer, Wi-Fi 360',
    pros: ['Buse Nextruder incroyable', 'Silencieuse', 'Excellente finition'],
    cons: ['Structure ouverte (caisson en option)'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'p-xl',
    brand: 'Prusa',
    name: 'Original XL',
    price: 2299,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '360x360x360mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Nextruder',
    nozzleDiameter: 0.6,
    multicolor: { supported: true, system: 'Toolchanger (1 à 5 têtes)' },
    newTech: 'Vrai changement d\'outils (Toolchanger) sans déchet',
    pros: ['Toolchanger sans purge de fil', 'Grand volume 360mm'],
    cons: ['Encombrante', 'Prix'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'p-coreone',
    brand: 'Prusa',
    name: 'Core One +',
    price: 1049,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '250x250x250mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'MMU3' },
    newTech: 'Boîtier fermé chauffé de conception Prusa CoreXY',
    pros: ['Première vraie Prusa CoreXY fermée', 'Excellente qualité'],
    cons: ['Tarif Prusa'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },
  {
    id: 'p-coreonel',
    brand: 'Prusa',
    name: 'Core One L',
    price: 1849,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '350x350x350mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'MMU3' },
    newTech: 'Format XL fermé avec contrôle thermique avancé',
    pros: ['Grand volume fermé Prusa'],
    cons: ['Investissement conséquent'],
    image: 'https://images.unsplash.com/photo-1544133782-960252033618?q=80&w=800'
  },

  // --- ELEGOO ---
  {
    id: 'e-centauri',
    brand: 'Elegoo',
    name: 'Centauri Carbon',
    price: 309,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Structure axe carbone ultra-légère CoreXY',
    pros: ['CoreXY fermé sous les 310€', 'Rapide et rigide'],
    cons: ['Monocouleur'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-centauri2',
    brand: 'Elegoo',
    name: 'Centauri Carbon 2',
    price: 339,
    comboPrice: 399,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'Elegoo Color Hub' },
    newTech: 'Elegoo Color Hub, portique carbone v2',
    pros: ['Excellente vitesse', 'Boîtier fermé', 'Boîtier couleur abordable'],
    cons: ['Nouveau système'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-centauri2open',
    brand: 'Elegoo',
    name: 'Centauri 2',
    price: 299,
    comboPrice: 349,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '256x256x256mm',
    filaments: ['PLA', 'PETG'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'Elegoo Color Hub' },
    newTech: 'CoreXY Open Frame',
    pros: ['CoreXY multicolore sous les 350€'],
    cons: ['Cadre ouvert'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-giga',
    brand: 'Elegoo',
    name: 'OrangeStorm Giga',
    price: 2738.97,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '800x800x1000mm',
    filaments: ['PLA', 'PETG', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier',
    nozzleDiameter: 0.6,
    multicolor: { supported: false },
    newTech: 'Volume géant d\'un mètre de haut (4 têtes simultanées)',
    pros: ['Impression géante 800x800x1000mm'],
    cons: ['Nécessite un grand atelier'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-n4',
    brand: 'Elegoo',
    name: 'Neptune 4',
    price: 189,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '225x225x265mm',
    filaments: ['PLA', 'PETG'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Klipper OS préinstallé',
    pros: ['Très bon prix d\'entrée', 'Klipper rapide'],
    cons: ['Slicer basique'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-n4p',
    brand: 'Elegoo',
    name: 'Neptune 4 Pro',
    price: 219,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '225x225x265mm',
    filaments: ['PLA', 'PETG', 'ABS'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Zones de chauffe segmentées, rails métal',
    pros: ['Rails métalliques fluides', 'Chauffe intelligente'],
    cons: ['Ventilateur bruyant'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-n4plus',
    brand: 'Elegoo',
    name: 'Neptune 4 Plus',
    price: 339,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '320x320x385mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Wi-Fi, Klipper high speed, volume 320mm',
    pros: ['Grand volume réactif'],
    cons: ['Empreinte au sol'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-n4max',
    brand: 'Elegoo',
    name: 'Neptune 4 Max',
    price: 439,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '420x420x480mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Volume XL 420mm avec accélérateur Klipper',
    pros: ['Massive et très stable'],
    cons: ['Temps de chauffe du plateau'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'e-n3p',
    brand: 'Elegoo',
    name: 'Neptune 3 Pro',
    price: 149,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '225x225x280mm',
    filaments: ['PLA', 'PETG'],
    maxNozzleTemp: 260,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Extrudeur direct-drive fiable',
    pros: ['Prix ultra accessible (149€)', 'Très facile'],
    cons: ['Vitesse classique'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },

  // --- QIDI TECH ---
  {
    id: 'q-max4',
    brand: 'Qidi Tech',
    name: 'Qidi Max 4',
    price: 1049,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '305x305x300mm',
    filaments: ['Techniques', 'PA-CF', 'PC', 'ABS'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Chambre activement chauffée à 65°C',
    pros: ['Parfaite pour filaments techniques', 'Grande solidité'],
    cons: ['Design massif'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'q-q2',
    brand: 'Qidi Tech',
    name: 'Qidi Q2',
    price: 379,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '200x200x200mm',
    filaments: ['PLA', 'PETG', 'ABS'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Structure cubique fermée compacte',
    pros: ['Fermée et compacte', 'Prix raisonnable'],
    cons: ['Volume 200mm'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'q-q2c',
    brand: 'Qidi Tech',
    name: 'Qidi Q2C',
    price: 379,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '200x200x200mm',
    filaments: ['PLA', 'PETG'],
    maxNozzleTemp: 260,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Cadre CoreXY ouvert',
    pros: ['Châssis rigide'],
    cons: ['Ouverte'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'q-q1pro',
    brand: 'Qidi Tech',
    name: 'Q1 Pro 3D',
    price: 549,
    discontinued: true,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '245x245x245mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'AI Cam, Klipper OS',
    pros: ['Chambre chauffée'],
    cons: ['Ancien modèle discontinué'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'q-plus4',
    brand: 'Qidi Tech',
    name: 'Qidi Plus 4',
    price: 699,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '280x280x280mm',
    filaments: ['Tous', 'Carbone'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Chambre chauffée 65°C, buse 350°C',
    pros: ['Excellents résultats sur ABS/ASA/PC'],
    cons: ['Pas de multicolore natif'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'q-plus5',
    brand: 'Qidi Tech',
    name: 'Qidi Plus 5',
    price: 749,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '300x300x300mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Chambre régulée thermique, nouveau moteur direct drive',
    pros: ['Grand volume fermé 300mm', 'Impression haute température'],
    cons: ['Assez lourde'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },
  {
    id: 'q-xmax3',
    brand: 'Qidi Tech',
    name: 'X-Max 3',
    price: 899,
    discontinued: true,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '325x325x315mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'CoreXY Industrial Grade',
    pros: ['Grand volume'],
    cons: ['Modèle discontinué'],
    image: 'https://images.unsplash.com/photo-1628143242784-90a8a6be97c9?q=80&w=800'
  },

  // --- FLASHFORGE ---
  {
    id: 'f-guider3u',
    brand: 'Flashforge',
    name: 'Guider 3 Ultra',
    price: 3499,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '330x330x600mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Dual Extruder, hauteur 60cm, vitesse extrême',
    pros: ['Volume vertical de 600mm', 'Extrudeur double'],
    cons: ['Tarif industriel'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'f-ad5x',
    brand: 'Flashforge',
    name: 'AD5X',
    price: 379,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '220x220x220mm',
    filaments: ['PLA', 'ABS'],
    maxNozzleTemp: 280,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Plateau flexible, Caméra HD intégrée',
    pros: ['Maniable', 'Nivellement automatique'],
    cons: ['Volume moyen'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'f-a5m',
    brand: 'Flashforge',
    name: 'Adventurer 5M',
    price: 299,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '220x220x220mm',
    filaments: ['PLA', 'PETG'],
    maxNozzleTemp: 280,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'CoreXY 600mm/s à prix plancher',
    pros: ['Extrêmement rapide sous les 300€'],
    cons: ['Châssis ouvert'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'f-a5mpro',
    brand: 'Flashforge',
    name: 'Adventurer 5M Pro',
    price: 499,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '220x220x220mm',
    filaments: ['Tous'],
    maxNozzleTemp: 280,
    maxBedTemp: 110,
    nozzleType: 'Inox',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Filtre HEPA double circulation, Silencieuse',
    pros: ['Sécurité en intérieur (HEPA)', 'Boîtier fermé silencieux'],
    cons: ['Volume 220mm'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'f-c5',
    brand: 'Flashforge',
    name: 'Creator 5',
    price: 779,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '300x300x300mm',
    filaments: ['Tous'],
    maxNozzleTemp: 320,
    maxBedTemp: 120,
    nozzleType: 'Industrial Acier',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Dual Core Processing, structure renforcée',
    pros: ['Grande stabilité', 'Matériaux techniques'],
    cons: ['Modèle imposant'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'f-c5pro',
    brand: 'Flashforge',
    name: 'Creator 5 Pro',
    price: 929,
    enclosed: true,
    structure: 'CoreXY',
    buildVolume: '320x320x350mm',
    filaments: ['Tous'],
    maxNozzleTemp: 350,
    maxBedTemp: 130,
    nozzleType: 'Industrial Acier',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'FF-Multi' },
    newTech: 'Gestion thermique active, plateau sous vide optionnel',
    pros: ['Fiabilité industrielle', 'Compatible multicolore'],
    cons: ['Poids élevé'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },

  // --- SOVOL ---
  {
    id: 's-sv08max',
    brand: 'Sovol',
    name: 'SV08 Max',
    price: 939,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '450x450x450mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Style Voron 2.4 CoreXY XL 450mm',
    pros: ['Volume Voron open source géant'],
    cons: ['Taille de la machine'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 's-sv08',
    brand: 'Sovol',
    name: 'SV08',
    price: 469,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '350x350x350mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Inspirée de Voron 2.4 open-source',
    pros: ['CoreXY 350mm très rapide', 'Excellente communauté open-source'],
    cons: ['Modèle ouvert'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 's-sv06lace',
    brand: 'Sovol',
    name: 'SV06 Plus ACE',
    price: 254,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '300x300x340mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'ACE System' },
    newTech: 'Volume 300mm compatible système couleur ACE',
    pros: ['Prix compétitif', 'Grand volume'],
    cons: ['Structure cartésienne classique'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 's-sv06ace',
    brand: 'Sovol',
    name: 'SV06 ACE',
    price: 209,
    enclosed: false,
    structure: 'Cartésienne XYZ',
    buildVolume: '220x220x250mm',
    filaments: ['PLA', 'PETG', 'TPU'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Laiton',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'Direct drive haute précision',
    pros: ['Super rapport qualité/prix à 209€'],
    cons: ['Ouverte'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },
  {
    id: 's-zero',
    brand: 'Sovol',
    name: 'Sovol Zero',
    price: 359,
    enclosed: false,
    structure: 'CoreXY',
    buildVolume: '180x180x180mm',
    filaments: ['PLA', 'PETG', 'ABS'],
    maxNozzleTemp: 300,
    maxBedTemp: 100,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: false },
    newTech: 'CoreXY ultra-compacte style Voron V0',
    pros: ['Ultra rapide et compacte'],
    cons: ['Petit volume'],
    image: 'https://images.unsplash.com/photo-1631034300431-7e04990928a3?q=80&w=800'
  },

  // --- SNAPMAKER ---
  {
    id: 'sm-u1',
    brand: 'Snapmaker',
    name: 'Snapmaker U1',
    price: 899,
    enclosed: false,
    structure: 'IDEX',
    buildVolume: '270x270x270mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 110,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'IDEX Double Tête' },
    newTech: 'Independant Dual Extruder (IDEX) pour 2 couleurs/matériaux sans purge',
    pros: ['Impression bicolore/support soluble rapide', 'Zéro déchet de purge'],
    cons: ['Cadre ouvert'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'sm-artisan-prem',
    brand: 'Snapmaker',
    name: 'Artisan Premium 3-in-1',
    price: 2699,
    enclosed: true,
    structure: 'Cartésienne XYZ',
    buildVolume: '400x400x400mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'Dual Extruder Module' },
    newTech: 'Machine 3-en-1 : Impression 3D 400°C, Gravure Laser 40W, Fraisage CNC 200W',
    pros: ['Atelier complet 3D + Laser 40W + CNC', 'Boîtier fermé géant', 'Qualité industrielle'],
    cons: ['Tarif pro'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  },
  {
    id: 'sm-artisan',
    brand: 'Snapmaker',
    name: 'Artisan 3-in-1',
    price: 2299,
    enclosed: true,
    structure: 'Cartésienne XYZ',
    buildVolume: '400x400x400mm',
    filaments: ['Tous'],
    maxNozzleTemp: 300,
    maxBedTemp: 120,
    nozzleType: 'Acier Trempé',
    nozzleDiameter: 0.4,
    multicolor: { supported: true, system: 'Dual Extruder Module' },
    newTech: 'Machine 3-en-1 : Impression 3D, Gravure Laser 10W, Fraisage CNC 200W',
    pros: ['Plateau géant 400mm', 'Modules interchangeables en 1 min'],
    cons: ['Poids important'],
    image: 'https://images.unsplash.com/photo-1631034301594-32b007137452?q=80&w=800'
  }
];

export const allRequestedPrinters: Printer[] = [...printers];

export const filaments: FilamentType[] = [
  { name: 'PLA', description: 'Le plus populaire, biodégradable et facile.', pros: ['Facile à imprimer', 'Pas d\'odeur', 'Précision'], cons: ['Fragile à la chaleur', 'Pas très solide'], difficulty: 1 },
  { name: 'PETG', description: 'Le juste milieu entre PLA et ABS.', pros: ['Solide', 'Résistant aux UV', 'Durable'], cons: ['Fils d\'ange (stringing)', 'Adhère trop'], difficulty: 2 },
  { name: 'PET', description: 'Version pure du PETG, souvent translucide.', pros: ['Recyclable', 'Clarté optique'], cons: ['Difficile à dompter'], difficulty: 3 },
  { name: 'ABS', description: 'Plastique industriel standard.', pros: ['Solide', 'Résiste à la chaleur', 'Lissable'], cons: ['Odeurs', 'Warping'], difficulty: 4 },
  { name: 'ASA', description: 'Le successeur de l\'ABS, résistant aux UV.', pros: ['Tenue extérieure parfaite', 'Mécanique'], cons: ['Warping'], difficulty: 4 },
  { name: 'TPU', description: 'Matériau flexible type caoutchouc.', pros: ['Incassable', 'Flexible'], cons: ['Très lent', 'Bouchage possible'], difficulty: 3 },
  { name: 'Nylon', description: 'Extrêmement solide et résistant à l\'usure.', pros: ['Durable', 'Faible friction'], cons: ['Hygroscopique', 'Warping'], difficulty: 5 },
  { name: 'PC', description: 'Polycarbonate pour une solidité maximale.', pros: ['Ultra résistant', 'Température'], cons: ['Très difficile'], difficulty: 5 },
  { name: 'PPS', description: 'Polymère haute performance industrielle.', pros: ['Chimiquement inerte', 'Stable'], cons: ['Prix industriel'], difficulty: 5 }
];

export const filamentBrands: FilamentBrand[] = [
  { name: 'Elegoo', pros: ['Prix imbattable', 'Fiabilité'], cons: ['Peu de couleurs'] },
  { name: 'Anycubic', pros: ['Accessible', 'Standard'], cons: ['Cassant'] },
  { name: 'Bambu Lab', pros: ['RFID', 'Enroulement', 'Qualité'], cons: ['Prix', 'Propriétaire'] },
  { name: 'Creality', pros: ['Standard', 'Pas cher'], cons: ['Qualité variable'] },
  { name: 'eSUN', pros: ['PLA+ reconnu', 'Choix'], cons: ['Bobines plastiques'] },
  { name: 'Prusament', pros: ['Précision ±0.02', 'Traçabilité'], cons: ['Cher'] },
  { name: 'Polymaker', pros: ['Technique', 'PolyTerra'], cons: ['Premium'] },
  { name: 'Rosa3D', pros: ['Couleurs Silk', 'Europe'], cons: ['Sourcing'] },
  { name: 'Sunlu', pros: ['Pas cher', 'Test'], cons: ['Enroulement'] },
  { name: 'GST 3D', pros: ['Kilo pas cher'], cons: ['Qualité'] },
  { name: 'Recreus', pros: ['Leader TPU'], cons: ['Cher'] },
  { name: 'Formfutura', pros: ['Exotique'], cons: ['Prix'] },
  { name: 'Overture', pros: ['Fiable', 'Tapis inclus'], cons: ['Basique'] }
];
